### ISSUE TITLE
Move an object

### ISSUE THREAD

**Issue by mlafefon** [4ian/GDevelop-extensions#10]
**⚠️ Please edit and complete this before submitting your extension:**
Move an object
## Describe the extension
Move an object back and forth/ Up and Down. with distance and force as parameters.
Trigger the effect by using the Move Object Left  To Right action or
Move Object Up  To Down action.
Good for using as a moving platform.
## Checklist

- [+ ] Extension has a proper name and description.
- [ +] Extension has tags (for example: "platform, brick, breakable").
- [+ ] All behaviors have a description.
- [+ ] All functions (actions, conditions, expressions) have descriptions.
- [+
 I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Extensionmovemove.zip](https://github.com/4ian/GDevelop-extensions/files/3253635/Extensionmovemove.zip)
 ]

**Comment by Ruhan777** [comment]
hOW TO USE THIS?

**Comment by mlafefon** [comment]
> hOW TO USE THIS?

There is a better extension called Linear Movement build in Gdevelop.

**Comment by 4ian** [comment]
Please ask questions on the forum instead. Also be mindful about the way you write: no all caps sentences. Thanks!
