### ISSUE TITLE
Toggle switch (new extension)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#103]
## Describe the extension
Toggle switch that users can click or touch
Add this behavior to a shape painter object.

When the toggle switch is in the LEFT position, the condition `Checked` is FALSE.
When the toggle switch is in the RIGHT position, the condition `Checked` is TRUE.
A halo appears when the mouse hovers near the toggle switch.

Toggle switch cannot be toggled by users if any of these are true:
- Toggle switch is hidden
- Toggle switch's layer is hidden
- Toggle switch is disabled

Toggle switch can always be changed by an action.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[ToggleSwitch-0.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5901265/ToggleSwitch-0.0.1.json.zip)

## Example Game

https://games.gdevelop-app.com/game-0de0a9a8-4f2b-48a6-9b5c-e75c1aa20ca5/index.html

## Video

https://user-images.githubusercontent.com/8879811/106405983-27c08d80-63f5-11eb-8e5b-37dc61f1a222.mp4

**Comment by 4ian** [comment]
A-maz-ing 😄

Great job! Could not find much things to change, I just reduced the description of the behavior because these descriptions are usually only a few lines long. But we would need to make the description of the extension easier to find from the behavior UI.

Apart from that, everything looks good, great descriptions, actions for everything, expressions for everything (I'll introduce later something to generate automatically conditions from the existing expressions :)), nicely done events... very nice 👍

**Comment by 4ian** [comment]
It's uploaded!

**Comment by tristanbob** [comment]
While creating an example game to show how to use this, I discovered that I missed some critical conditions.

## Version 0.0.2

Added missing conditions
- IsChecked
- IsDisabled

## Extension file
[ToggleSwitch-0.0.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/5916634/ToggleSwitch-0.0.2.json.zip)

**Comment by Bouh** [comment]
I take care of update this extension, indeed these conditions are very useful haha!

**Comment by 4ian** [comment]
Indeed ^^ Thanks Bouh, I've seen this yesterday and forgot to do the update.
