### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by Rtv666** [4ian/GDevelop-extensions#109]
Handle text input with limited characters (can adjust preset to 8)
Text entry activator (could be set as invisible field)
This fixes on enter press new line issue for accepting data.
Saves to global variable which can be used for player name storage or highscore data.

Please let me know if you find this useful or can help me improve this system.

Rico Searle 
rtv666@hotmail.com

## Checklist
[Text Limiter.zip](https://github.com/4ian/GDevelop-extensions/files/6121189/Text.Limiter.zip)

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Finally, attach the .json file of your extension here.

You also may have to create an account on GitHub before posting.
If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by Rtv666** [comment]
Loving Gdevelop 
Hope this meets standards - my first attempt

**Comment by Rtv666** [comment]
ahhh sorry just testing wont work now

**Comment by tristanbob** [comment]
> ahhh sorry just testing wont work now

What do you mean?

**Comment by tristanbob** [comment]
@Rtv666 This extension looks unfinished.  Do you want to keep it open?  

This issue will be closed in 30 days without an update.

**Comment by Midhil457** [comment]
It has been over a month, I think this can be closed now
