### ISSUE TITLE
Extension update:  SineMovement (add functions to set properties)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#110]
## Changelog

Added functions to set all of the behavior properties
- SetInitialX
- SetInitialY
- SetAmplitudeX
- SetAmplitudeY
- SetSineSpeed

## Extension file

[SineMovementExtension_0.0.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/6138748/SineMovementExtension_0.0.3.json.zip)

## Screenshot

![Screenshot 2021-03-14 220446](https://user-images.githubusercontent.com/8879811/111102362-83605980-8511-11eb-89fe-f935b88b8af6.jpg)

**Comment by 4ian** [comment]
Sounds good to me :) 
Making me think that I should really add a way to generate a expression + condition using a single function.

**Comment by Bouh** [comment]
Extension updated!
Thx for this update :)
