### ISSUE TITLE
Generate parcour

### ISSUE THREAD

**Issue by gamepanter** [4ian/GDevelop-extensions#111]
This extension generates random parcour

[generate parcour.zip](https://github.com/4ian/GDevelop-extensions/files/6172510/generate.parcour.zip) 🙌

**Comment by Bouh** [comment]
We do not retain this extension for the following reasons:
- The presentation of this extension is not clear.
- The extension does not follow [the recommended practices.](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices)
- There is no context in which this extension can be used.

If you wish to resubmit the extension for verification open another application following the pre-filled instructions.

Thanks for you paticence and your time.
