### ISSUE TITLE
Rotate objects around player

### ISSUE THREAD

**Issue by VegeTato** [4ian/GDevelop-extensions#116]
## Describe the extension
This extension will help in making objects rotates around another objects(could be player) or any object
for example: making shields that rotates around the player to protect him from enemies upcoming bullets
*Can take up to 3 objects to rotates
*Users can set the Speed of the rotating objects around the player
*Users can set the Distance between the objects and the player

## Checklist
- [ Check] Extension has a proper name and description.
- [Check ] Extension has tags (for example: "platform, brick, breakable").
- [Check ] All behaviors have a description.
- [ Check] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [Check ] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [ Check] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Rotate Objects around player Extension.zip](https://github.com/4ian/GDevelop-extensions/files/6239498/Rotate.Objects.around.player.Extension.zip)

                                         Gif shows the Extension job in action:
![ExtensionReview](https://user-images.githubusercontent.com/81715237/113212469-7bc5e200-927f-11eb-94d2-bd528820c3fa.gif)

**Comment by tristanbob** [comment]
Great work @VegeTato!  I am going to look at this (hopefully) tonight.  Based on our discussion on Discord, here are some ideas I will look into:

- [ ] Let users specify the quantity of orbiting objects 
- [ ] Make sure users can increase/decrease that number and objects get created/deleted automatically
- [ ] Add a StartingOffset so users can use this extension multiple times (so they can use different objects)
- [ ] Tristan just might make a model of the solar system with accurate orbit speeds (but not distance or sizes)

**Comment by tristanbob** [comment]
Good news, I got all my desired functionality working!  @VegeTato this version will let you use multiple objects at the same time on the same center object, but you will need to specify a StartingOffset and use a unique OrbitID string.

### Version 0.3.0

Run this extension on every frame to make the orbiting objects move.
This extension will create/delete orbiting objects to match the quantity specified. 
Use the delete function or set quantity to 0 to remove orbiting objects.

Extension parameters include:
- Center object
- Orbiting object (cannot be the same as the Center object)
- Number of orbiting objects
- Distance from the center object
- Speed of the orbiting objects (degrees per second).  Use negative numbers to orbit in the opposite direction.
- Speed to rotate each orbiting object (degrees per second).  Use negative numbers to rotate in the opposite direction.
- Starting offset and OrbitID are only needed if different objects orbit the same center object at the same time.

Example uses:
- Make shield objects around the player to protect from enemies
- Weapons that damage enemies when they collide
- Can be used on both player and NPC objects 
- A visual indicator of ammo quantity or health points
- Interesting animations that can function as a pulsating single entity (using short distances) 

### Extension file
[OrbitingObjectsExtension_0.3.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6293882/OrbitingObjectsExtension_0.3.0.json.zip)

### Example game
https://victrisgames.itch.io/extension-orbiting-objects

### Video
https://user-images.githubusercontent.com/8879811/114340990-ff9c8b80-9b15-11eb-9bbe-f3d827a13bca.mp4

**Comment by VegeTato** [comment]
WOW ! it looks just PERFECT ! ❤️ 
great work !
Thank you for upgrading it to the MAXIMUM level ! 😄
hopefully they add it in the extensions of Gdevelop ^_^

**Comment by tristanbob** [comment]
@4ian - This extension is ready for your review.  Thanks!

**Comment by Bouh** [comment]
- When a variable is directly passed to an action, take the type directly.
`Rotation speed of objects (angle)` 
Angle of what?
This can be reused.
![image](https://user-images.githubusercontent.com/1670670/114540648-12b67500-9c56-11eb-91d9-1cf2a2cc9ce2.png)

- Starting offset (degrees)
=> Starting offset (angle in degrees)

- Layer that orbiting objects will be created on
=> Add somewhere that the default layer will be used, maybe use the wording like in center camera action
```(base layer if empty)```


- There is a way to add long descriptions on input fields.
![image](https://user-images.githubusercontent.com/1670670/114539941-4775fc80-9c55-11eb-87ed-6bdd89f299a1.png)

You can use it for explain more how to use **OrbitID** on both actions.

**Comment by 4ian** [comment]
Looks like a great extension! Happy to add it.
Bouh remarks would be good to address. A rotation speed is indeed something that should be in "degrees per second".

> Starting offset (angle in degrees)

I would rather say `Angle start offset (in degrees)`? We always put just the unit in parenthesis. E.g: (in pixels), (in degrees), (in degrees per second)...

> There is a way to add long descriptions on input fields

Yep that's good to use I think. :)

The example is nice in any case! We could also include it in GDevelop examples.

**Comment by tristanbob** [comment]
I will update this extension tonight with the wording suggestions, and with using the long description (as needed).  

I'll tag 4ian again when I have the new version uploaded.  Thanks for the review and kind words!

**Comment by 4ian** [comment]
Excellent!

**Comment by tristanbob** [comment]
### Version 0.3.1

- Wording changes suggested by reviewers

### Extension file

[OrbitingObjectsExtension_0.3.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6308009/OrbitingObjectsExtension_0.3.1.json.zip)

@4ian this is ready for another round of reviews.  :)

**Comment by arthuro555** [comment]
There is a slight problem, __OrbitingObjects.OrbitQuantity can get out of sync if the user deletes an orbiting object. This makes the extension believe there is a specific amount of objects when there isn't.

Replicate: Take the example from @tristanbob, add this event:
![image](https://user-images.githubusercontent.com/19349038/114858507-d582ec00-9de9-11eb-82d7-7ed616f21844.png)
Start a preview, hover over a few dinos, then play with the quantity slider. As you can see, it doesn't reflect the amount of objects anymore.

**Comment by tristanbob** [comment]
Interesting use-case, thanks for testing! 

Do you think I should be able to count the number of OrbitingObjects that are linked to each CenterObject?

```
ForEach(CenterObject):
Condition:
Take Into Account "OrbitingObjects" Linked to "CenterObject"
Action:
Set Variable(CanICountThisWay) to count(OrbitingObjects)
```

I think I have tried this method but it didn't work.  :-/

**Comment by tristanbob** [comment]
I have rewritten this extension to use the Count() function to track linked objects, instead of using a manual variable.  The makes the extension smaller and simpler.  However, I am going to pause working on this extension until I learn more about this bug:

https://github.com/4ian/GDevelop/issues/2560

**Comment by tristanbob** [comment]
Alright, I've made a lot of improvements and I'm ready for more excellent feedback!

## Version 0.5.0
- Migrated from using a variable to simply counting the linked instances (much simpler)
- Added a boolean option to not reset the position of objects when the quantity decreases (might work well for health/ammo)
- Tested more use-cases (but I would love for more ideas to be tested!)

## Extension file

[OrbitingObjectsExtension_0.5.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6330587/OrbitingObjectsExtension_0.5.0.json.zip)

## Updated game

https://victrisgames.itch.io/extension-orbiting-objects

**Comment by arthuro555** [comment]
After a quick look, this looks good to me!

**Comment by tristanbob** [comment]
Thanks for reviewing this @arthuro555!  

@4ian We are ready for your review of this extension.

**Comment by 4ian** [comment]
Great! I'll check that :) 👍👍

**Comment by 4ian** [comment]
I've made a few changes in the description ("Run this extension" => "Run the action" (an extension is a set of action/condition/behavior, but we don't say to users to "run an extension", this can be confusing)). But apart from that this is very nice!
Added it to the registry 👍 

Thanks all!!
