### ISSUE TITLE
Input Validation Extension

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#117]
## Describe the extension
Adds several functions to check if strings contain valid information in them. For example, an email, or url, and also some additional functions to do some string formatting like removing new lines, or converting to alphanumeric. I can't take all the credit for this extension @arthuro555 also made several of the functions.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[InputValidation.zip](https://github.com/4ian/GDevelop-extensions/files/6246046/InputValidation.zip)

**Comment by 4ian** [comment]
Nice work! :)
Thanks @Add00 and @arthuro555! I've added it to the registry.

I've made a few changes:

* Careful about your description: "Provides multiple expressions that remove unwanted characters from a string such as non-alphanumerical characters or new Lines. and additional, has expressions to check if strings are vaild emails or urls.". Missing or extra capital letters, "and additional" is not proper english.
  * I've changed this to "Provides conditions to check if a string is a valid phone number, url, email, number, contains only letters. Also provides expressions to manipulate strings (count number of lines, remove new lines, remove non alphanumerical characters).". Be descriptive :) 
* `IsValidPhoneNum` => don't use abbrevations. Changed to `IsValidPhoneNumber`.
* "Convert any nonalphanumeric characters into alphanumeric characters" => that's false, i've replaced by "Remove any non-numerical and non A-Z characters".
* "Check if a string has only numbers" -> this seems not entirely true too. The code is checking if the string is representing a number. I've changed the description and renamed to "IsValidNumber"

Be careful about this kind of polishing, this is what distinguish from an extension that would look a bit unprofessional from a really good and robust one :) I know it's not fun, but every sentence and description must be perfect ;)

Thanks again for working on this, will be very useful!
