### ISSUE TITLE
Update to ToggleSwitch (version 0.0.3)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#118]
## Version 0.0.3

- Fixed a bug in the SetDisabled and SetChecked functions caused by a copy/paste from the Checkbox extension.  This bug caused ToggleSwitches to ONLY work when the Checkbox extension was installed at the same time.
 
## Extension file

[ToggleSwitch-0.0.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/6251769/ToggleSwitch-0.0.3.json.zip)

**Comment by 4ian** [comment]
Updated, thanks for spotting this! :)
