### ISSUE TITLE
Screen Wrap Around

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop-extensions#119]
Objects leaving one side of the screen immediately reappear on the opposite side, maintaining speed and trajectory.
By default, the borders of this area match the screen size, but they can be changed.
The teleport happens when the center of the object crosses a border.  The TriggerOffset property can be used to modify (increase or decrease) the position of when the teleport is triggered.

From trello card:
https://trello.com/c/c7mAzEBM/64-screen-wrap-around

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

Extension:
[ScreenWrapExtension_0.1.5.zip](https://github.com/4ian/GDevelop-extensions/files/6262207/ScreenWrapExtension_0.1.5.zip)

Extension Example:
[ScreenWrapGame_0.1.5.zip](https://github.com/4ian/GDevelop-extensions/files/6262209/ScreenWrapGame_0.1.5.zip)

**Comment by 4ian** [comment]
Looks absolutely great! I'm looking at it now :) I think we can remove the limitation of the behavior to sprites, it can actually work for any object :)

**Comment by 4ian** [comment]
Added! I wonder if we could also adapt this so that the borders are following the camera of a layer? Though we can do this manually with the properties.
Anyway, looks pretty good already! 👍
