### ISSUE TITLE
Custom Cursor

### ISSUE THREAD

**Issue by HarshRajSinghania** [4ian/GDevelop-extensions#12]
## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[CustomCursor.json.zip](https://github.com/4ian/GDevelop-extensions/files/3292898/CustomCursor.json.zip)

**Comment by AlexSmart6667** [comment]
i had the same idea

so i made it

**Comment by Bouh** [comment]
This extension can be condensed to a single action.
![image](https://user-images.githubusercontent.com/1670670/110002614-dcf8a500-7d15-11eb-905a-1892fd67d1a6.png)
Thanks for your time on it but there is nothing more simple.
