### ISSUE TITLE
TimedBackAndForth update

### ISSUE THREAD

**Issue by PascalLadalle** [4ian/GDevelop-extensions#120]
A user on the Discord complained that the extension was not compatible with pause (time scale at 0).
I have added a check for that.
I also reworked the events, added comments and changed the timer because it was reset when an obstacle was met, so the object remained stuck there for a whole cycle duration.
I'm wondering if I should also edit the fact that animations should face left. I think I kept this from the extension I used as base, but anims should usually be facing right by default. Is this a breaking change I should avoid?

[Extension1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6321359/Extension1.1.json.zip)

**Comment by 4ian** [comment]
> I'm wondering if I should also edit the fact that animations should face left. I think I kept this from the extension I used as base, but anims should usually be facing right by default. Is this a breaking change I should avoid?

Correct, we should change this! Even if it's a breaking change it's alright because it's mostly used as a new extension, and if people update they will have to change their animation names but that's not a huge deal.

**Comment by PascalLadalle** [comment]
👍 
Here's the update.
[Extension1.11.json.zip](https://github.com/4ian/GDevelop-extensions/files/6324402/Extension1.11.json.zip)

**Comment by Bouh** [comment]
- A paragraph is in double.
- The version number is still 0.0.1, please up the version when the change are public.
- The start orientation could be define by a checkbox for keep the mechanics is the previous games?

![image](https://user-images.githubusercontent.com/1670670/115018606-5ad4d200-9eb8-11eb-8455-d9160e701d82.png)

**Comment by PascalLadalle** [comment]
My goal at first was only to update the back and forth extension, so I guess I kept the left-facing because I didn't want to alter it too much, but it was a bad idea. We should encourage right-facing animations everywhere, in accordance with the "basic game concepts" wiki page.
The timer changes I introduced in this update may bring a minor breaking change in some projects, so I guess it's a good time to introduce a big breaking change. 😅  
I have shortened the short description and changed the version :)
[Extension1.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6324682/Extension1.0.1.json.zip)

**Comment by tristanbob** [comment]
Backward compatibility is a good goal to reduce user confusion, but we should not be afraid to change things if it improves the extension in the long term.  Fortunately for extensions, there really isn't a "breaking" change.  By default, games will keep using the installed extension version and will never upgrade unless manually performed by the game dev.

**Comment by 4ian** [comment]
Yep let's go for this "breaking" change and make the behavior to be "right-facing". I made a wrong choice previously of making it left-facing by default.
As Tristan said, this is fortunately not breaking really anything, so let's do it (and we can be more cautious in the future with very popular extensions).

**Comment by Bouh** [comment]
ok I''ll take care of updating the extension with the previous zip file in the post above.

**Comment by Bouh** [comment]
[The new version 1.0.1 is updated](https://github.com/4ian/GDevelop-extensions/commit/08ae70bc321a4bea39e884c4675f3bb8b833a941) :white_check_mark:

**Comment by 4ian** [comment]
🎉
