### ISSUE TITLE
New extension: Turret movement

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#121]
## Describe the extension
A turret movement with acceleration and stop angles

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/u2097nr24pp8v5x/Turret.zip?dl=1

It's used by this example: https://github.com/4ian/GDevelop/issues/2566

## Idea box
* New "Move clockwise/counter-clockwise" actions that has a parameter from 0 to 1 to allow analogs inputs.
* An new action could be added for AI to target an object by taking into account it's velocity to aim in from of it and following it at a lower speed to avoid oscillations.

**Comment by 4ian** [comment]
Very nice! :) Added to the registry!

I made a few typo fixes:

There is stop angles, the angle is born by them => There are stop angles, the angle is bounded by these.
No stop angles, use mod to avoid the angle to becom to much big => Use mod to avoid the angle value to be too large.
Speed Maxium => Maximum speed
degree per second => degrees per second
Angle maximum => Maximum angle

> An new action could be added for AI to target an object by taking into account it's velocity to aim in from of it and following it at a lower speed to avoid oscillations.

Interesting, could be a smart turret :) 

Thanks a lot, very nice to see this high quality extension. I'll review your other submissions as soon as I can!
