### ISSUE TITLE
New extension: Mouse movement conditions

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#123]
## Describe the extension
Conditions over mouse movement
* Mouse is moving
* Mouse has staid still for a given duration

I think it would make sense to merge the double click extension and this one into a new one.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

https://www.dropbox.com/s/9v13exvpnovw7b3/MouseMovement.zip?dl=1

It's used by this example: https://github.com/4ian/GDevelop/issues/2566

**Comment by 4ian** [comment]
Nice! I've renamed everything to be "Cursor" instead of "Mouse", as in the future we might want to put more emphasis on the notion of "Cursor"/"pointer" rather than a mouse (which can be a touch instead).
Thanks!!
