### ISSUE TITLE
New extension (Pause/Unpause)

### ISSUE THREAD

**Issue by Zimquadery** [4ian/GDevelop-extensions#129]
## Describe the extension
two actions that allows to pause or unpause the scene or a specific layer. One action for the scene and other for a layer.

## Checklist

- [yes] Extension has a proper name and description.
- [yes] Extension has tags (for example: "platform, brick, breakable").
- [no] All behaviors have a description. (this extension has no behaviors)
- [ yes] All functions (actions, conditions, expressions) have descriptions.
- [yes] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Pause_Unpause.zip](https://github.com/4ian/GDevelop-extensions/files/6365086/Pause_Unpause.zip)

**Comment by Bouh** [comment]
Thank you for your suggestion.
This is a lightweight extension that points to an interesting request.

Two actions are included for toggle a state, here the speed of a scene and a layer.

A toggleable state is very common in the events sheets, it would be nice to think to a generic and integrated solution in the engine.

A bit like loop events an state event or a toggleable event could be useful for reducing superfluous variables mandatory for create a toggleable state.

If a new event type is unnecessary, we would approve a ton of little extension like this one over time.

This kind of extension is for know the best solution, If there is no objection I'll review it and merge.

**Comment by 4ian** [comment]
For something like this which is a few actions, I would rather have an article on the wiki explaining how to do this.
Otherwise we're promoting another level of abtraction which is not providing much value I'm afraid.

**Comment by Bouh** [comment]
There a[ wiki page about states.](http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/how-to-make-togglable-states-with-variables#how_to_toggle_states_using_variables)

**Comment by 4ian** [comment]
I was picturing a "how to" page about "How to implement a pause in your game?" :) Can be done in two ways: pausing and launching a new scene, or setting the timescale to 0 for a layer, and not running the event for the gameplay.

**Comment by Bouh** [comment]
This extension will not be approved because it is just a "wrapper" extension.
It is still welcome to discuss to read others points of view, after that we will evaluate the situation again.
