### ISSUE TITLE
Camera Shake 2.5.0 (update)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#130]
## Changes

- Fix drift when using position shake
- Add option to shake forever (boolean)

Note: This extension still cannot shake multiple layers at the same time, but I will work on that later.

## Extension file

[CameraShakeExtension_2.5.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6370901/CameraShakeExtension_2.5.0.json.zip)

## Example game

https://victrisgames.itch.io/gdevelop-camera-shake-example

**Comment by 4ian** [comment]
Updated 👍👍
