### ISSUE TITLE
New extension: Snap to hexagonal grids

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#131]
## Describe the extension
It allow to snap object on
* Pointy topped hexagonal grid
* Flat topped hexagonal grid
* Bubble grid

Check it out with this example: https://github.com/4ian/GDevelop/issues/2586
It's also used by this match-3 example: https://github.com/4ian/GDevelop/issues/2566 

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/5wrk4kcz01swdcf/HexagonalGrid.zip?dl=1

**Comment by 4ian** [comment]
Very nice! Added 👍
