### ISSUE TITLE
Updated extension: Add offsets to the "snap to grid" extension

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#132]
## Describe the extension
It adds offset parameters and remove the usage of an internal variable.

Check it out with this example: https://github.com/4ian/GDevelop/issues/2586

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/npcz0iodrlz70gp/SnapToGrid.zip?dl=1

**Comment by 4ian** [comment]
Updated, thanks! 👍
