### ISSUE TITLE
Follow Multiple Objects With Camera

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#133]
## Authors
Jeroen Erkens, Tristan Rhodes (https://victrisgames.itch.io/)

## Description
Follow multiple objects with camera

Change the zoom and position of the camera to keep all instances of an object (or object group) on the screen

Notes:
- This function is meant to be run on every frame.
- Use conditions to limit which instances will be tracked by the camera.
- Use an object group to track multiple objects.
- Only run on one layer at a time.  If multiple layers need to move the same way, create events that copy CameraX, CameraY, and CameraZoom values.
- Can be used on a single object instance to move the camera smoothly.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[FollowObjectsWithCamera_0.1.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6402827/FollowObjectsWithCamera_0.1.0.json.zip)

## Example game
https://games.gdevelop-app.com/game-a577735f-9b70-4b1f-93b3-428b469ee514/index.html

## Game source code
[MoveAndZoomCameraToKeepObjectsOnScreen.zip](https://github.com/4ian/GDevelop-extensions/files/6402811/MoveAndZoomCameraToKeepObjectsOnScreen.zip)

## Video 
https://user-images.githubusercontent.com/8879811/116644454-a06db200-a930-11eb-8a79-893694cbf1dc.mp4

**Comment by Bouh** [comment]
The number from cameras always 0 for GD5, I would see it more at the end of the sentence between brackets or just hidden until this parameter come useable.
That parameter is a remaining part of GD4 not used in GD5.

![image](https://user-images.githubusercontent.com/1670670/116663921-0b060880-a998-11eb-9669-0bc5b926d6ee.png)

**Comment by tristanbob** [comment]
Good idea!  I have removed that parameter from the function sentence, but it's still a valid parameter in case cameras are added in the future.

## Version 0.1.1

- Removed camera parameter from function sentence
![Screenshot 2021-05-02 134330](https://user-images.githubusercontent.com/8879811/116825493-d4bdba00-ab4c-11eb-9067-f5e9474e3756.jpg)

## Extension file

[FollowObjectsWithCamera_0.1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6412131/FollowObjectsWithCamera_0.1.1.json.zip)

**Comment by 4ian** [comment]
Looks like a great extension :) 

One thing that might be worth looking at, you use __FollowObjects.MaxZoom variable but you never set it it seems, and you use `GetArgumentAsNumber("MaxZoom")` in the condition... is there some confusion there? That's probably the reason why the clamp is not working?
![image](https://user-images.githubusercontent.com/1280130/117575333-3f38a200-b0d9-11eb-8c85-ad2b78f17ec9.png)

**Comment by tristanbob** [comment]
Good catch!  Yes, I needed to copy the function parameter to that variable.  The clamp() event is now working, which I think is more elegant than the two events I was using.

### Version 0.1.2

- Replaced two events with a single event that uses clamp()

### Extension file

[FollowObjectsWithCamera_0.1.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/6448114/FollowObjectsWithCamera_0.1.2.json.zip)

**Comment by 4ian** [comment]
Excellent! I did a few changes in the description and sentence (to add units in the sentence notably. Also to talk about an "action", not a "function").
Also careful, when a custom lerp speed was entered, then the lerp speed variable was never set and so stayed to 0.

Apart from this, great extension! 👍 Will be very useful for a lot of games.

**Comment by tristanbob** [comment]
Shoot!  That is the exact same problem I had with MaxZoom.  I installed the version you added and I see you fixed it for me.  Thanks!

Tristan
