### ISSUE TITLE
Camera Shake v2.6.0

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#135]
## Changes in version 2.6.0

- Changed the initial shake to always be based on the amplitude value.  This enables users to use positive or negative amplitude values for a single shake effect that can be used for quick impacts/hits/recoil.  This use case is described in the description.
- Shake now works as intended even if the camera is rotated and/or zoomed during a shake 
- Fixed bug that caused amplitude to increase when "time between shakes" increased
- Fixed bug with "shake forever" when a new shake was triggered while one was already in progress, the shake would stop.
- Simplified complex events and updated comments

## Extension file

[CameraShakeExtension_2.6.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6412815/CameraShakeExtension_2.6.0.json.zip)

## Future Tasks
- Port these improvements to the Shake Object extension (soon)
- Enable shaking on multiple layers at once (not soon)

**Comment by tristanbob** [comment]
## Version 2.6.1

- Removed the shake timer reset when the shake function is started.  Previously, the shake could move too far if a new shake was started before a shake movement could complete.

## Extension file

[CameraShakeExtension_2.6.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6414954/CameraShakeExtension_2.6.1.json.zip)

**Comment by 4ian** [comment]
Thanks for working on this! I think these changes are great, I've updated the extension :)
