### ISSUE TITLE
Emoji Extension

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#136]
## Describe the extension
A simple extension that adds two ways of displaying emoji characters in GDevelop.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Emoji.zip](https://github.com/4ian/GDevelop-extensions/files/6416246/Emoji.zip)

**Comment by Bouh** [comment]
I've made some edits and added approved the extension.
Thanks for your time!
