### ISSUE TITLE
New extension - Advanced Circle Movement

### ISSUE THREAD

**Issue by Manuel-Ti** [4ian/GDevelop-extensions#137]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
Advanced Circle Movement
Values that can be set: AngleX, AngleY, OriginX, OriginY, RadiusX, RadiusY, SpeedX, SpeedY, RotateClockwise/RotateCounterClockwise

Forum post: https://forum.gdevelop-app.com/t/example-advanced-circle-movement/32361

## Checklist

- [ ] Extension has a proper name and description.
- [ ] Extension has tags (for example: "platform, brick, breakable").
- [ ] All behaviors have a description.
- [ ] All functions (actions, conditions, expressions) have descriptions.
- [ ] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Finally, attach the .json file of your extension here.
[AdvancedCircleMovementExtension.zip](https://github.com/4ian/GDevelop-extensions/files/6419899/AdvancedCircleMovementExtension.zip)

You also may have to create an account on GitHub before posting.
If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by D8H** [comment]
That looks great.
There is another extension with different features but in the same area. I seems to me that what you did could work very well with this:
https://github.com/4ian/GDevelop-extensions/issues/116

**Comment by tristanbob** [comment]
Welcome @Manuel-Ti !  Thank you so much for your extension.  I love the example game you made, it clearly shows what this extension can do.  

I think this could be used to upgrade the SineMovement extension (and not the OrbitingObjects extension).  Your extension adds one unique (and fun) feature to the SineMovement extension:  You can set different speeds for X and Y movement.  This is what lets you do the figure 8 motion, which is not possible on the current version of SineMovement.

I'll see will test adding this feature to SineMovement and report back here.

**Comment by tristanbob** [comment]
Initial tests are good. 

https://user-images.githubusercontent.com/8879811/117242788-2dae7c00-adf3-11eb-9d30-407893e1d2c9.mp4

**Comment by tristanbob** [comment]
I think this issue can be closed with the improvements added to SineMovement:
https://github.com/4ian/GDevelop-extensions/issues/145
