### ISSUE TITLE
Mouse Helper Extension

### ISSUE THREAD

**Issue by Lim98SE** [4ian/GDevelop-extensions#138]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
A small extension for help with the mouse.

## Checklist

- [X ] Extension has a proper name and description.
- [ ] Extension has tags (for example: "platform, brick, breakable").
- [X ] All behaviors have a description.
- [ X] All functions (actions, conditions, expressions) have descriptions.
- [ X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[MouseHelper.zip](https://github.com/4ian/GDevelop-extensions/files/6428049/MouseHelper.zip)

**Comment by Lim98SE** [comment]
{
  "author": "Lim98SE",
  "description": "An extension with functions to help with the mouse. Allows to make buttons, mouse cursors, mouse pets, and other things.",
  "extensionNamespace": "",
  "fullName": "Mouse Helper",
  "helpPath": "https://lucid-meitner-d7a4e1.netlify.app/help.html",
  "iconUrl": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmVyc2lvbj0iMS4xIiBpZD0ibWRpLW1vdXNlIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTExLDEuMDdDNy4wNSwxLjU2IDQsNC45MiA0LDlIMTFNNCwxNUE4LDggMCAwLDAgMTIsMjNBOCw4IDAgMCwwIDIwLDE1VjExSDRNMTMsMS4wN1Y5SDIwQzIwLDQuOTIgMTYuOTQsMS41NiAxMywxLjA3WiIgLz48L3N2Zz4=",
  "name": "MouseHelper",
  "previewIconUrl": "https://resources.gdevelop-app.com/assets/Icons/mouse.svg",
  "shortDescription": "An extension to help with controlling the mouse.",
  "version": "1.0.0",
  "tags": [
    "Mouse"
  ],
  "dependencies": [],
  "eventsFunctions": [
    {
      "description": "Checks if an item is clicked.",
      "fullName": "Is Clicked?",
      "functionType": "Condition",
      "name": "IsClicked",
      "private": false,
      "sentence": "Is _PARAM1_ clicked?",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [
            {
              "type": {
                "inverted": false,
                "value": "SourisSurObjet"
              },
              "parameters": [
                "object",
                "",
                "",
                ""
              ],
              "subInstructions": []
            },
            {
              "type": {
                "inverted": false,
                "value": "MouseButtonPressed"
              },
              "parameters": [
                "",
                "Left"
              ],
              "subInstructions": []
            }
          ],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "SetReturnBoolean"
              },
              "parameters": [
                "True"
              ],
              "subInstructions": []
            }
          ],
          "events": []
        }
      ],
      "parameters": [
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Object/Group",
          "longDescription": "",
          "name": "object",
          "optional": false,
          "supplementaryInformation": "",
          "type": "objectList"
        }
      ],
      "objectGroups": []
    },
    {
      "description": "Makes an object go to the mouse.",
      "fullName": "Go to Mouse",
      "functionType": "Action",
      "name": "GoToMouse",
      "private": false,
      "sentence": "Bring _PARAM1_ to the mouse.",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "MettreXY"
              },
              "parameters": [
                "object",
                "=",
                "MouseX()",
                "=",
                "MouseY()"
              ],
              "subInstructions": []
            }
          ],
          "events": []
        }
      ],
      "parameters": [
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Object/Group",
          "longDescription": "",
          "name": "object",
          "optional": false,
          "supplementaryInformation": "",
          "type": "objectList"
        }
      ],
      "objectGroups": []
    },
    {
      "description": "Checks if the mouse is clicking.",
      "fullName": "Is Clicking?",
      "functionType": "Condition",
      "name": "IsClicking",
      "private": false,
      "sentence": "Checks for mouse clicks.",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [
            {
              "type": {
                "inverted": false,
                "value": "MouseButtonPressed"
              },
              "parameters": [
                "",
                "Left"
              ],
              "subInstructions": []
            }
          ],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "SetReturnBoolean"
              },
              "parameters": [
                "True"
              ],
              "subInstructions": []
            }
          ],
          "events": []
        }
      ],
      "parameters": [],
      "objectGroups": []
    },
    {
      "description": "Checks if the mouse is clicking once.",
      "fullName": "Is Clicking? (Cooldown)",
      "functionType": "Condition",
      "name": "IsClickingCooldown",
      "private": false,
      "sentence": "Is the mouse clicking with a cooldown?",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [
            {
              "type": {
                "inverted": false,
                "value": "MouseButtonPressed"
              },
              "parameters": [
                "",
                "Left"
              ],
              "subInstructions": []
            },
            {
              "type": {
                "inverted": false,
                "value": "BuiltinCommonInstructions::Once"
              },
              "parameters": [],
              "subInstructions": []
            }
          ],
          "actions": [],
          "events": []
        }
      ],
      "parameters": [],
      "objectGroups": []
    },
    {
      "description": "Follow the mouse.",
      "fullName": "Follow Mouse",
      "functionType": "Action",
      "name": "FollowMouse",
      "private": false,
      "sentence": "Makes _PARAM1_ follow the mouse.",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "Tween::AddObjectPositionTween"
              },
              "parameters": [
                "object",
                "tween",
                "\"gotoMouse\"",
                "MouseX()",
                "MouseY()",
                "\"linear\"",
                "100",
                ""
              ],
              "subInstructions": []
            }
          ],
          "events": []
        }
      ],
      "parameters": [
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Object",
          "longDescription": "",
          "name": "object",
          "optional": false,
          "supplementaryInformation": "",
          "type": "objectList"
        },
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Tween Behaviour",
          "longDescription": "",
          "name": "tween",
          "optional": false,
          "supplementaryInformation": "Tween::TweenBehavior",
          "type": "behavior"
        }
      ],
      "objectGroups": []
    },
    {
      "description": "Allows for the creation of a cursor.",
      "fullName": "Mouse Cursor",
      "functionType": "Action",
      "name": "MouseCursor",
      "private": false,
      "sentence": "Makes a mouse cursor from _PARAM1_.",
      "events": [
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "MettreXY"
              },
              "parameters": [
                "obj",
                "=",
                "MouseX()",
                "=",
                "MouseY()"
              ],
              "subInstructions": []
            }
          ],
          "events": []
        },
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [
            {
              "type": {
                "inverted": false,
                "value": "GetArgumentAsBoolean"
              },
              "parameters": [
                "\"hide\""
              ],
              "subInstructions": []
            }
          ],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "CacheSouris"
              },
              "parameters": [
                ""
              ],
              "subInstructions": []
            }
          ],
          "events": []
        },
        {
          "disabled": false,
          "folded": false,
          "type": "BuiltinCommonInstructions::Standard",
          "conditions": [
            {
              "type": {
                "inverted": true,
                "value": "GetArgumentAsBoolean"
              },
              "parameters": [
                "\"hide\""
              ],
              "subInstructions": []
            }
          ],
          "actions": [
            {
              "type": {
                "inverted": false,
                "value": "MontreSouris"
              },
              "parameters": [
                ""
              ],
              "subInstructions": []
            }
          ],
          "events": []
        }
      ],
      "parameters": [
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Object",
          "longDescription": "",
          "name": "obj",
          "optional": false,
          "supplementaryInformation": "",
          "type": "objectList"
        },
        {
          "codeOnly": false,
          "defaultValue": "",
          "description": "Hide Mouse?",
          "longDescription": "",
          "name": "hide",
          "optional": false,
          "supplementaryInformation": "",
          "type": "yesorno"
        }
      ],
      "objectGroups": []
    }
  ],
  "eventsBasedBehaviors": []
}

**Comment by D8H** [comment]
Thanks for sharing.
What conditions or actions does the extension contains?
Do you have a small project that can be used to see how it works?

**Comment by Lim98SE** [comment]
> 
> 
> Thanks for sharing.
> What conditions or actions does the extension contains?
> Do you have a small project that can be used to see how it works?

1. It has things that allow for creation of a mouse cursor from an object, detecting if an object is clicked, making an object follow the mouse, ect.
2. A demo can be found [here](https://lim95.itch.io/space-shooter).

**Comment by Bouh** [comment]
Hello thx for you time on this extension.
Unfortunately I'm not convinced of its usefulness, most of the functions you add just wrap another action or condition.

For example "Go to Mouse" function change only the position of an object, it's one action.
"Is Clicking?" wrap one condition for "touch or mouse left is pressed".
And so ones.

**Comment by Bouh** [comment]
> Working on updating this with a new version adding more functions for Button and Cursor behaviors and tidying up the extension.

Yes sure, think to download the current extension, add your stuff inside and submit the edited extension here ;)

**Comment by Lim98SE** [comment]
[mh1.1.zip](https://github.com/4ian/GDevelop-extensions/files/6612272/mh1.1.zip)
I changed a lot and added functions, like checking if a mouse was clicked (Left, Middle, Right, or any), same for a button, hiding/showing the cursor object, checking if a button is hovered, ect.

**Comment by Lim98SE** [comment]
> 
> 
> > Working on updating this with a new version adding more functions for Button and Cursor behaviors and tidying up the extension.
> 
> Yes sure, think to download the current extension, add your stuff inside and submit the edited extension here ;)

It's done, can't wait for 1.1 to get onto GDevelop!
