### ISSUE TITLE
Updated extension : add path finding movement to Linked Object Tools

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#140]
## Describe the extension
This is an update to: https://github.com/4ian/GDevelop-extensions/issues/122
It add a path finding movement behavior that uses objects links (instead of obstacles for the other behavior, the interface is almost the same) and new conditions.

An example that shows how to do unit movement for tactical games use it (https://github.com/4ian/GDevelop/issues/2612)
I think it could be useful for point and click to bypass obstacles with a predetermined polygonal chain, so I might do another example for this one day.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/dyjlfzc2ok6f6dd/LinkTools.zip?dl=1

## Idea box
City builders may need new actions to evaluate access to some service with proximity or fields. My next goal is to do tiny city builder example to check this.

**Comment by 4ian** [comment]
That's one very advanced extension :) Updated! Thanks 👍
