### ISSUE TITLE
Mouse Helper 2.0

### ISSUE THREAD

**Issue by Lim98SE** [4ian/GDevelop-extensions#143]
## Describe the extension
An update to my Mouse Helper extension with more things, like behaviors. New functions are:

1. Draw Line to Mouse (Shape Painter)
2. Button Behavior (Any Object)
3. Cursor Behavior (Any Object)

## Checklist

- [ ] Extension has a proper name and description.
- [ ] Extension has tags (for example: "platform, brick, breakable").
- [ ] All behaviors have a description.
- [ ] All functions (actions, conditions, expressions) have descriptions.
- [ ] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[mh.zip](https://github.com/4ian/GDevelop-extensions/files/6461228/mh.zip)

**Comment by Lim98SE** [comment]
> 
> 
> Can you details what's new?
> And complete the checklist before asking a review.
> Give a proper title to this issue is also welcome.

I just did. I have also affirmed it all works and would be willing to put an example to show off the extension.

**Comment by Bouh** [comment]
This extension has been added to GDevelop with the name **Mouse Helper**.
Next time please read the [guide of the best pratices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices) before submit your extension.
