### ISSUE TITLE
Updated extension: distance evaluation for Linked Object Tools

### ISSUE THREAD

**Issue by D8H** [4ian/GDevelop-extensions#144]
## Describe the extension
This is an update to: https://github.com/4ian/GDevelop-extensions/issues/122 and https://github.com/4ian/GDevelop-extensions/issues/140
It add
* an action get the distance of the instance that has been traveled
* actions to link neighbors on rectangular grids, isometric grids and hexagonal grids.

http://wiki.compilgames.net/doku.php/gdevelop5/all-features/extensions/linked-objects-tools

An example that shows how to evaluate distance by roads to define rules for city builders uses it (https://github.com/4ian/GDevelop/issues/2638)

## **Checklist**

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
https://www.dropbox.com/s/dyjlfzc2ok6f6dd/LinkTools.zip?dl=1

## Idea box
I think it could be useful for point and click to bypass obstacles with a predetermined polygonal chain, so I might do another example for this one day.

**Comment by 4ian** [comment]
Closing as added through a PR
