### ISSUE TITLE
SineMovement 0.0.5

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#145]
## Version 0.0.5

Allow an object to move smoothly on the X and/or Y axis following a sine wave.

Example uses:
- Floating objects, such as powerups or coins
- Moveable platforms
- Enemy movement patterns

Properties:
- Center of movement, X position
- Center of movement, Y position
- Horizontal distance
- Vertical distance
- Horizontal speed
- Vertical speed

Tips:
- For circular or elliptical movement, the horizontal and vertical speed need to be the same
- For horizontal movement only, set vertical distance to 0
- For vertical movement only, set horizontal distance to 0
- For figure-8 movement, set horizontal speed to 1/2 of the vertical speed

# Example game
https://victrisgames.itch.io/extension-sinemovement-and-deptheffect

# Extension file
[SineMovementExtension_0.0.5.json.zip](https://github.com/4ian/GDevelop-extensions/files/6468657/SineMovementExtension_0.0.5.json.zip)

# Video
https://user-images.githubusercontent.com/8879811/118032950-726f7100-b325-11eb-8f78-de0856ce99a2.mp4

**Comment by Bouh** [comment]
I've made small edits on description value like:
![image](https://user-images.githubusercontent.com/1670670/118333708-74dfef80-b50c-11eb-81e3-7e042b0b4e75.png)

Otherwise, it's a great improvement, thanks for your time!
Approved and merged!

**Comment by 4ian** [comment]
Thanks both 👍
