### ISSUE TITLE
DepthEffect: Change scale based on Y position to simulate depth of field

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#146]
## Describe the extension

The scale of the object decreases the closer it is to the horizon, giving the illusion that the object is travelling away from the viewer.

Properties:
- Horizon Y position (Default: 0)
- Max scale of the object when it is at the bottom of the screen (Default: 1)
- Y exponent can be used to control the rate of change  (Default: 2)

Tips:
- If you want speed to look constant, be sure to reduce the object's speed based on scale or Y value.  If you don't do this, the object will appear to be moving faster when it is near the top of the screen.  This matches how objects appear in the real world.
- This extension works well with the Y-sort extension, which changes Z order based on Y position.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[DepthEffectExtension_0.0.4.json.zip](https://github.com/4ian/GDevelop-extensions/files/6470231/DepthEffectExtension_0.0.4.json.zip)

## Game example
https://victrisgames.itch.io/extension-sinemovement-and-deptheffect

**Comment by tristanbob** [comment]
Do you think I should rewrite this to use width and height instead of scale?  

I could save the W and H values in the OnCreation function, and by avoiding using the scale() function, this could be applied to all objects (I think).

**Comment by tristanbob** [comment]
@4ian This extension is ready for review.  It includes two behaviors, one for sprites and one for text objects.

**Comment by 4ian** [comment]
Thanks for pinging me! I think it works well like this, and it's clean. I added it to the registry :)
