### ISSUE TITLE
Hash Extension

### ISSUE THREAD

**Issue by DrZanuff** [4ian/GDevelop-extensions#152]
## Describe the extension
Generate a Hash from a string, using Javascript.

## Checklist

- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions.
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[GenerateHash.json.zip](https://github.com/4ian/GDevelop-extensions/files/6526325/GenerateHash.json.zip)

**Comment by arthuro555** [comment]
- MD5 is not a secure hashing algorithm, I would rather recommend something like sha256
- Please specify the hash algorithm somewhere in the extension, it is very rare to just need to hash something without knowing the algorithm, most of the time you want to know it.

**Comment by DrZanuff** [comment]
- Added description about the type of algorithm
- Added sha256 algorithm, now the extension has two expressions (MD5 and SHA256) 

[GenerateHash.zip](https://github.com/4ian/GDevelop-extensions/files/6488652/GenerateHash.zip)

**Comment by Bouh** [comment]
Thank you guys, the extension is now in the application!
