### ISSUE TITLE
Shake Object (version 1.5.4)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#153]
## Version 1.5.3

- Includes all the upgrades to [Camera Shake v2.6.0](https://github.com/4ian/GDevelop-extensions/issues/135)
- Changed the initial shake to always be based on the amplitude value. This enables users to use positive or negative amplitude values for a single shake effect that can be used for quick impacts/hits/recoil. This use case is described in the description.
- Shake now works as intended even if the object is rotated and/or resized during a shake
- Fixed bug that caused amplitude to increase when "time between shakes" increased
- Fixed bug with "shake forever" when a new shake was triggered while one was already in progress, the shake would stop.
- Simplified complex events and updated comments

## Game example and source files
https://victrisgames.itch.io/gdevelop-camera-shake-example

## Extension file
~~[ShakeObjectExtension_1.5.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/6490384/ShakeObjectExtension_1.5.3.json.zip)~~

**Comment by tristanbob** [comment]
Pause on updating this, I found a corner-case bug.

**Comment by tristanbob** [comment]
## Version 1.5.4

- Fixed bug:  Starting a position shake with zero amplitude while a position shake is in progress causes the drift tracking variables to not be applied properly. 

## Extension file
[ShakeObjectExtension_1.5.4.json.zip](https://github.com/4ian/GDevelop-extensions/files/6490919/ShakeObjectExtension_1.5.4.json.zip)

**Comment by 4ian** [comment]
Updated! Thanks :)
