### ISSUE TITLE
Camera Shake (version 2.6.3)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#154]
## Version 2.6.3
- Improved description for extension and function, including more tips
- Updated comments in the code
- Matched code formatting of Object Shake so these will be easier to maintain

## Game Example and Source Files
https://victrisgames.itch.io/gdevelop-camera-shake-example

## Extension file
[CameraShakeExtension_2.6.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/6490392/CameraShakeExtension_2.6.3.json.zip)

**Comment by 4ian** [comment]
Great improvements, thanks!
