### ISSUE TITLE
Rectangular Movement

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#155]
## Describe the extension

Allow an object to move in a rectangular pattern.
By default, movement will slow down when going around corners, but this can be changed to use a constant speed.

Example uses:
- Moveable platforms
- Enemy movement patterns

Properties:
- Center of movement, X position
- Center of movement, Y position
- Horizontal distance
- Vertical distance
- Horizontal speed
- Vertical speed
- Use constant speed (object will not slow down at corners)
- Use counter-clockwise direction

Tips:
- Set the CenterX and CenterY values to move the object

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
~~[RectangularMovementExtension_0.1.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6527275/RectangularMovementExtension_0.1.0.json.zip)~~

## Game Example
https://victrisgames.itch.io/extension-rectangular-movement

## Video
https://user-images.githubusercontent.com/8879811/119242684-3f935d00-bb1d-11eb-891e-243cea7f4f5d.mp4

**Comment by tristanbob** [comment]
## Version 0.1.2

- Now works when speed and distance values are set to 0 for one direction

## Extension file
[RectangularMovementExtension_0.1.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/6527359/RectangularMovementExtension_0.1.2.json.zip)

**Comment by tristanbob** [comment]
## Version 0.1.2

- Now works when speed and distance values are set to 0 for one direction

## Extension file
[RectangularMovementExtension_0.1.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/6527359/RectangularMovementExtension_0.1.2.json.zip)

**Comment by 4ian** [comment]
Very nice! I've added it to the registry, with a few minor changes.

I have the impression that if the center x/y is left to 0, it's not using the object position as the center - despite an event made specially for this. Can you double check? Maybe this event is run too late.
