### ISSUE TITLE
FaceForward: Face object towards the direction of movement

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#156]
## Describe the extension

Set the angle of the object to match the direction of movement.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
~~[FaceForwardExtension_0.1.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6528855/FaceForwardExtension_0.1.0.json.zip)~~

## Game example
https://victrisgames.itch.io/extension-faceforward

## Video
https://user-images.githubusercontent.com/8879811/119275130-8beba500-bbd0-11eb-800c-06670fb97b7a.mp4

**Comment by 4ian** [comment]
Nice!
Could we use the object center (new expressions CenterX(), CenterY() since beta 110)? In 99% this should give the appropriate results, because the center is the center of rotation.

**Comment by tristanbob** [comment]
Good idea!  I forgot that feature was added; it is a very useful thing that will enable more extensions that work with ANY object type.

Now we just need Scale() functions added to all objects!  ;)

## Version 0.1.1

- Changed from using Object.X() to Object.CenterX() and Object.Y() to Object.CenterY()

## Extension file
[FaceForwardExtension_0.1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6529095/FaceForwardExtension_0.1.1.json.zip)

**Comment by 4ian** [comment]
Yep this will be useful for I think a lot of extensions. For example, I think we should update the "Screen Wrap" extension to use this :) Much more predictable and simpler to use.

As for this extension, it's great! Simple and clean. Added it 👍👍
