### ISSUE TITLE
Homing Projectile: Make a projectile object move towards a target object

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#158]
## Describe the extension
This extension requires two actions to function correctly:
1) "Lock projectile to target" should be used once per projectile. 
2) "Move projectile towards target" should be run every frame.  This will move all projectiles that are locked to targets.

Parameters:
- Rotation Speed: How fast the projectile rotates. This is critical in determining how fast the projectile can turn corners.
- Initial Speed: Starting speed of the projectile
- Acceleration: How much speed is added over time
- Max Speed:  The max speed a projectile can travel (does not apply to physics object)
- Max Lifetime:  The number of seconds a projectile can exist after locking onto a target.  Once this time is reached the object is deleted.

Tips:
- Make sure to set the angle of the projectile before you use the "Move" action.  The projectile will turn towards the target, but you might want the projectile to be facing a certain direction. 
- Since Max Speed is not enforced on the physics object, you can accomplish this by changing Linear Decay on the Physics behavior
- Use the lifetime parameter to prevent missiles from chasing objects forever

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[HomingProjectileExtension_0.1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6603160/HomingProjectileExtension_0.1.1.json.zip)

## Game example
https://victrisgames.itch.io/extension-homing-projectile

## Video
https://user-images.githubusercontent.com/8879811/120903848-d542e800-c605-11eb-907c-7b217016abe2.mp4

**Comment by 4ian** [comment]
Looks great! Great work, as usual :) 

I've seen that you used the mass to have an impulse of ~constant length across objects. How did you come up with this result? We could add a Mass expression maybe too, to avoid doing the manual work you did of computing density*width*height.

Anyway, for now I've added the extension! 👍

**Comment by tristanbob** [comment]
I agree that the Physics Behavior needs a Mass expression.  I used the AABB area to calculate mass, but that is only accurate if the user has not changed the physics collision mask.  I will create an issue to track this idea.
