### ISSUE TITLE
RPG gdevelop 5 extension

### ISSUE THREAD

**Issue by dokkogames** [4ian/GDevelop-extensions#163]
extension description:
An extension useful to create easy an RPG style character similar wich mario bros 3 map

behaviours of extension:

MovingRPG

Extension file:

https://www.mediafire.com/file/rbrrb9q8dubjjc5/RPG+character.json/file

**Comment by 4ian** [comment]
Can you describe more what's inside the extension and why it's useful? Do you have an example? :)

**Comment by Lim98SE** [comment]
Call it RPGD5
