### ISSUE TITLE
Orbit Objects Extension bug fix: Event sheet sentence parameters mixed up

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop-extensions#164]
Bug fix, the event sheet sentence had the parameters mixed up

![Orbit2](https://user-images.githubusercontent.com/73597906/122663108-bfacf100-d1b5-11eb-8ad8-c0482bdb0e0b.PNG)

Before:
![Orbit1](https://user-images.githubusercontent.com/73597906/122663110-c3407800-d1b5-11eb-859d-f1f31ace35d0.PNG)

Now:
![orbit3](https://user-images.githubusercontent.com/73597906/122663182-2e8a4a00-d1b6-11eb-81d3-a25c4712778e.PNG)

## Extension file
[OrbitingObjects.zip](https://github.com/4ian/GDevelop-extensions/files/6681769/OrbitingObjects.zip)

:)

**Comment by 4ian** [comment]
Thanks a lot 👍

This is fixed. We should think about a way to store somewhere the contributions like this for everyone, so that this can be recognized somewhere (and not just with a "author" field) :)
