### ISSUE TITLE
Rectangular flood fill: Create fill objects that cover the rectangular area of target objects

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#166]
## Warning
This extension requires another extension ("Create multiple copies of an object") in order to function correctly.  This dependency checking hasn't been automated, so it will rely on users reading the description.  If needed, I am OK holding on this extension until that capability is added.

## Describe the extension

Create fill objects that cover the rectangular area of target objects

How To Use:
- Place target objects in the scene in the places you want fill objects to be created
- This action only needs to be run once (at the beginning of the scene or using TriggerOnce)

Requirements:
- Extension "Create Multiple Copies of Object" must be installed

Object variables (Fill objects): 
- "CreationID" (number)
- "RowID" (number)
- "ColumnID" (number)
- "BatchID" (text)

Tips:
- Use fill objects that are the same size as the scene editor grid.  This will make sure the fill objects fit exactly inside the target objects.
- Hide target objects at the beginning of the scene if you don't want them to be visible.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[RectangularFloodFillExtension_1.0.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6706206/RectangularFloodFillExtension_1.0.0.json.zip)

## Game example
https://games.gdevelop-app.com/game-77cac788-e2c5-47dd-9820-e0eeaaa7cb4d/index.html

## Video
https://user-images.githubusercontent.com/8879811/123202778-73420980-d472-11eb-8b79-35b206d0355b.mp4

**Comment by Midhil457** [comment]
Hi! 

> This extension requires another extension ("Create multiple copies of an object") in order to function correctly

So, why don't you add the that function to this extension and remove it when dependencies are automated? The create copies extension only has a single function so it should be relatively easy. I tested it and it works without a problem

- Adding a random fill might be useful. As it can be used to populate top down games with foliage, etc... it might be suited to make another extension. but, it is your choice

- One suggestion I would give is to change the icon, as the extension is a rectangular fill tool (and not a hexagonal fill), something like this would be more apt

![RectangleFillGrid](https://user-images.githubusercontent.com/73597906/123230250-ac22c280-d4f4-11eb-993c-21278c5936ac.PNG)

:)

**Comment by tristanbob** [comment]
@Midhil457 thanks for your great insight.  I have made the changes you recommended:

## Version 1.1.0

- Changed icon to one of the grid icons
- Copy/Pasted the CreateMultipleCopiesOfObject Extension (and changed the reference to it)
- This means there is no longer an external dependency.  Once dependencies are supported, we should change this extension to refer to other extension.

## Extension file
[RectangularFloodFillExtension_1.1.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6722346/RectangularFloodFillExtension_1.1.0.json.zip)

## Game example 

Note: This also includes a handful of WIP extensions.
[RectangularFloodFill-1.1.0.zip](https://github.com/4ian/GDevelop-extensions/files/6722350/RectangularFloodFill-1.1.0.zip)

**Comment by Midhil457** [comment]
Hi again,

- You can make the MultipleCopies function private if you don't want the user to be able to use it or it to show up in the events selector
- One suggestion I forgot to add; The sentence in the events sheet could be 

    **Create _PARAM2_ that will cover _PARAM1_.  Space between rows:  _PARAM3_  Space between columns: _PARAM4_ Layer: _PARAM5_ Z-order: _PARAM6_ BatchID: _PARAM7_** 

    or 

     **Fill _PARAM1_ with _PARAM2_.  Space between rows:  _PARAM3_  Space between columns: _PARAM4_ Layer: _PARAM5_ Z-order: _PARAM6_ BatchID: _PARAM7_**

again it's your choice

:)

**Comment by 4ian** [comment]
Very nice! (as usual :))
@tristanbob do you want to do these latest changes according to @Midhil457 feedback? Then we can go ahead and add this 👍👍

**Comment by tristanbob** [comment]
Yes, I do.  I expect I will get this updated tonight!

**Comment by tristanbob** [comment]
Thank you @Midhil457 for helping polish this extension!

## Version 1.1.1

- Changed "CreateMultipleCopies" function to private (so users don't get confused if they also have that extension installed)
- Cleaned up the event sentence a little by removing extra words:
 `Create _PARAM2_ objects that will cover _PARAM1_ objects.  Space between rows:  _PARAM3_  Space between columns: _PARAM4_ Layer: _PARAM5_ Z-order: _PARAM6_ BatchID: _PARAM7_`

## Extension file

[RectangularFloodFillExtension_1.1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6752137/RectangularFloodFillExtension_1.1.1.json.zip)

**Comment by 4ian** [comment]
Thanks both, great job as usual :) I've added the extension.
