### ISSUE TITLE
Update DragCameraWithPointer Extension to use Option and Layer parameter types instead of normal string

### ISSUE THREAD

**Issue by Midhil457** [4ian/GDevelop-extensions#171]
Replaced normal string parameters with Layer and Options parameter. Changed the events to fit this change

## Extension file
[DragCameraWithPointer.zip](https://github.com/4ian/GDevelop-extensions/files/6740697/DragCameraWithPointer.zip)

**Comment by 4ian** [comment]
Excellent, great stuff! Updated 👍
