### ISSUE TITLE
Mouse teail extension

### ISSUE THREAD

**Issue by mlafefon** [4ian/GDevelop-extensions#18]
Use a sprite as an mouse trail
![_Preview-of-Project_-2019-08-29-09-13-39_Trim](https://user-images.githubusercontent.com/51256464/63935421-15a32880-ca66-11e9-9df1-5cdd644c4338.gif)

This is how to implement
![ביאור 2019-08-29 140207](https://user-images.githubusercontent.com/51256464/63935251-c230da80-ca65-11e9-8f5f-c93baeebef36.png)

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Extensionmosetrail.zip](https://github.com/4ian/GDevelop-extensions/files/3555251/Extensionmosetrail.zip)

**Comment by 4ian** [comment]
Nice :) A few feedbacks:
* There is a typo in the function name
* Could you avoid using a scene variable called "size" at all?
* Could you avoid having the first event launched only at the beginning of the scene? Hiding the cursor is not mandatory, we can let the user do it.
* The "trail long" parameter is confusing. Could we instead have a speed? Also you must use `TimeDelta()` when changing the scale of the object to be sure that this speed will be the same on every computers/refresh rate.

**Comment by mlafefon** [comment]
Good remarks
The ideal thing is to do this as a behavior with parameters, but I cannot create an object within the behavior.
I will Chang according to your remarks
Thanks

**Comment by jumpingjh** [comment]
Wow ! That's amazing.

Is it possible to disassociate mouse and effect. Example: I want to use the "ghost effect" in a platform game where the player run ?

**Comment by mlafefon** [comment]
> Wow ! That's amazing.
> 
> Is it possible to disassociate mouse and effect. Example: I want to use the "ghost effect" in a platform game where the player run ?

I'll try to make it generic as possible
