### ISSUE TITLE
New extension - AdvancedPlatformCamera

### ISSUE THREAD

**Issue by NicolaLC** [4ian/GDevelop-extensions#19]
## AdvancedPlatformCamera [1.0.1.0]
Adds some cool improvements to camera follow behavior:

1. Interpolated __dynamic zoom__
    You can set a dynamic zoom during the game to the camera, the current camera zoom will interpolate to the target one, adding a cool effect
2. Interpolated __position following__
    Camera will follow the player with interpolation, so it will be less static and more dynamic, adding a realistic camera follow effect to the game

Check the extended description and changelogs [here](https://forum.gdevelop-app.com/t/new-advancedplatformcamera-behavior/20528)

## Extension file
[apc.zip](https://github.com/4ian/GDevelop-extensions/files/3595107/apc.zip)

**Comment by 4ian** [comment]
Sorry for the wait, I'll take a look today :)

**Comment by 4ian** [comment]
Looks nice! A few remarks:

For the behavior description:
> Advanced utilies for platformer camera (and others kind of player)

Could we put something more descriptive (Set the camera to follow the specified object with smooth transitions between positions and zooms)?

All of the actions are for the base layer, should we add a parameter to each action to enter the layer name? There is a "Layer" parameter type so it will be easy to use, and by default will be the base layer :)

**Comment by tristanbob** [comment]
@NicolaLC do you think the "[Follow Multiple Objects With Camera](https://github.com/4ian/GDevelop-extensions/issues/133)" extension will meet your needs?  It can be used to follow a single object instance, and it uses lerp() to make the camera move smoothly.

**Comment by arthuro555** [comment]
Hello, I checked this out and as far as I see this is just wrappers for camera actions that add lerp. I think it is a good concept if it was actually like in the presentation video: a behavior you put on a sprite with the platformer behavior and that handles all the camera movement afterwards. Here, it still leaves so much work to do that it hardly shortens or simplifies anything. I therefore reject it.
