### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by MauryDev** [4ian/GDevelop-extensions#21]
## Extension Description
This extension makes life easier for those using GDevelop and Kongregate API JS.

This feature helps communicate with Kongregate with Gdevelop. Lots of functions to make GDevelop easy to use Kongregate API.

Version: 1.0.0

Functions:
1- Load API (Action)
2- Stats submit (Action)
3- Services ResizeGame (Action)
4- Services IsGuest (Condition)
5- Services GetUserId (Expression)
6-  Services_GetUsername (Expression String)
7- Services GetGameAuthToken (Expression String)
8- Check if variable "kogregateAPI" Work

## Extension file

[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/3618461/Extension.zip)

**Comment by 4ian** [comment]
Published :) I made several changes to the name of action/condition - names must be English names and same for sentences displayed in the events sheet.

Thanks a lot for your work on this! Will be very useful for people wanting to integrate their games with Kongregate!
