### ISSUE TITLE
Interact for Battery,Language and OnLine

### ISSUE THREAD

**Issue by MauryDev** [4ian/GDevelop-extensions#22]
Battery API for GDevelop:
Description:

Extension to access battery properties.

Methods:
API Start (Action)
API Done (Condition)
Level (String Expression)
Charging (Condition)
Charging Time (String Expression)
Discharging Time (String Expression)

Events:
onchargingtimechange (Condition)
onlevelchange (Condition)
ondischargingtimechange (Condition)
onchargingchange (Condition)

JSON file:
https://gitlab.com/maurygta2/interact-for-gdevelop/blob/master/src/Battery.json

Language API for GDevelop:

Description:
Information about the user's language.

Methods:
Language (String Expression)

JSON file:
https://gitlab.com/maurygta2/interact-for-gdevelop/blob/master/src/language.json

OnLine API for GDevelop:

Description:
Extension to check if it is online.

Methods:
OnLine (String Expression)

JSON file:
https://gitlab.com/maurygta2/interact-for-gdevelop/blob/master/src/online.json

**Comment by 4ian** [comment]
Thanks for these! Unfortunately I can't your json files, seems that the repository is private. Can you make it public? :)

**Comment by MauryDev** [comment]
Yes,sorry.

JSON files: https://gitlab.com/maurygta2/interact-for-gdevelop/blob/master/src

**Comment by 4ian** [comment]
Great! Are these working the browser only or also in Cordova? I guess it's browser only for now :)

**Comment by MauryDev** [comment]
Browser, Cordova and Electron.

**Comment by 4ian** [comment]
Ok :) I'll review these and will publish them then!

**Comment by Bouh** [comment]
The [battery API is depreciated](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API ).

**Comment by arthuro555** [comment]
As Bouh said, the Battery API is deprecated so we should probably not use it. The language extension is in my opinion a bit too barebones, I would rather wait for a more complete i18n extension to be made. The online extension is OK I think, though navigator.onLine isn't reliably testing for connection as it only checks the network adapter status, which will be always true (always "online") if it is a virtual one like when using virtual box or some VPNs. I am unsure whether we should not publish it as well or just add a warning in the description.

**Comment by 4ian** [comment]
Looks too error prone, and I think we already have an extension checking if we're online now?
I would not publish this for now then.

**Comment by Bouh** [comment]
Yes and on the same model, so the current extension may not work everywhere.

![image](https://user-images.githubusercontent.com/1670670/124023653-7303ba00-d9ee-11eb-99f2-c850883ed30b.png)
