### ISSUE TITLE
[Update] 0.0.2 TextEntryVirtualKeyboard 

### ISSUE THREAD

**Issue by Bouh** [4ian/GDevelop-extensions#24]
## Describe the extension
Page on forum about this extension : 
https://forum.gdevelop-app.com/t/extension-keyboard-for-mobile/22186

This is an improvement of my previous extention for open keyboard on mobile.
This add support for open custom keyboard like : tel, number, text (by default).
This version have been tested on my phone, Android 9.

## Extension file
[Extension002.zip](https://github.com/4ian/GDevelop-extensions/files/3799973/Extension002.zip)

Edit : One user have a issue with numbers,  when he press any number, it wasn't input.
Under samsung, android 9

**Comment by 4ian** [comment]
Have you found how to solve the issue reported by the user?

**Comment by Bouh** [comment]
Not yet.
When i use ` textEntry.setString(input.value)`  input.value is empty with number keyboard, but the input contain the numbers and signs. 

[Code on Pastebin](https://pastebin.com/raw/VFscrFg9)

![image](https://user-images.githubusercontent.com/1670670/68094479-2c6c5e00-fea1-11e9-971a-049d4486ea8a.png)

**Comment by 4ian** [comment]
Maybe we should still go ahead with this as this can be useful for users?

**Comment by Bouh** [comment]
Yes it's requested by people and probably used, the problem is that under iPhone the keyboard doesn't open.

I had found an example code that works.
I had tested with an iPhone on browserstack but my implementation had given nothing.

https://forum.gdevelop-app.com/t/mobile-keyboard-extension/21348

**Comment by Bouh** [comment]
I need feedbacks and someone testing it on iOS.

New version [you can try here online.](http://witly.fr/export_keyboard/)

Extension file .json :  [textentryvirtualkeyboard.zip](https://github.com/4ian/GDevelop-extensions/files/4010425/textentryvirtualkeyboard.zip)
Entire project from example online : [Keyboard_mobile_fix_0.0.3b.zip](https://github.com/4ian/GDevelop-extensions/files/4010427/Keyboard_mobile_fix_0.0.3b.zip)

**Comment by 4ian** [comment]
Thanks for this new version! Unfortunately I don't have an iOS device with iOS 13. I tried with an iPhone simulator but not keyboard is shown when tapping the text boxes. It's running iOS 11 though, so fairly "old", we should try with iOS 13 (usage of older iOS version is too low, we should target the latest one)

**Comment by CJCShadowsan** [comment]
Just as a quick question here in case...

...I got a version of this working but not sure if it's 0.0.3b or the 0.0.2 so firstly, how do I check that?

Secondly...

I tried applying this to a Facebook Instant Games app - and whilst it accepts input in a laptop fine, it doesn't bring up the keyboard when published using Facebook. 

Any thoughts?

I heavily suspect there's some sort of overdraw happening in facebook instant games that prevents the keyboard showing up but if someone could confirm for me that would be good.

Happy to test anything to get it working - else i'm going to have to code a keyboard UI into my game to draw from within the game...

**Comment by Bouh** [comment]
Hi @CJCShadowsan  You can follow the [step 1 here](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/share#export_your_extension) for know the version number of the extension.

For the keyboard in Facebook Instant Game i guess the create element textfield in the HTML body is blocked/hidden by Facebook, so the focus can't be done on a hidden element.

Unfortunately this virtual keyboard extension is very hacky and deserve some new research for find a workaround on each platform.

**Comment by CJCShadowsan** [comment]
I genuinely think it'd be a UI overlay on a layer that is consistent in all
apps.

As much as I'd love to integrate with users own systems I suspect an
integrated UI approach would be the only consistent method as it would work
in every app, as it would be drawn in-app.

**Comment by Bouh** [comment]
Note : 

Instead hide the input in the HTML and open the keyboard, maybe show the input over the canvas at the position of the object in the IDE, and custom the input with css from the properties of the behavior or object. This way the keyboard will be always open, and this avoid to the user to use a Text object for display the values from the keyboard.

If this works this mean anykind of DOM elements can be used. But need an implementation in GD directly as a new object.
