### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by arthuro555** [4ian/GDevelop-extensions#26]
Maybe you could set up a CI to automatically call the script and push it nack but to another branch, and make the pull requests and pushs of extensions directly to the other branch watched by the CI?

**Comment by 4ian** [comment]
Yes I could, for now it's simple enough so that it was not too much of a problem but using Travis-CI/CircleCI/Semaphore or even GitHub actions to automate this will be welcome at some point :)

There is already extensive CI running for GDevelop for each commit and pull request.

**Comment by Bouh** [comment]
There is Github Actions for this :)

**Comment by arthuro555** [comment]
Closing this as I think it is better to keep the issues tab for actual extensions submissions and nobody seems to be interested in working on that.
