### ISSUE TITLE
Align Object

### ISSUE THREAD

**Issue by grymmjack** [4ian/GDevelop-extensions#30]
Aligns objects within the scene or screen.

ToSceneCentered: horizontally and vertically centered in scene
ToSceneTop: vertically to the top in scene
ToSceneMiddle: vertically to the middle in scene
ToSceneBottom: vertically to the bottom in scene
ToSceneLeft: horizontally to the left in scene
ToSceneRight: horizontally to the right in scene
ToSceneCenter: horizontally to the center in scene

ToScreenCentered: horizontally and vertically centered in screen
ToScreenTop: vertically to the top in screen
ToScreenMiddle: vertically to the middle in screen
ToScreenBottom: vertically to the bottom in screen
ToScreenLeft: horizontally to the left in screen
ToScreenRight: horizontally to the right in screen
ToScreenCenter: horizontally to the center in screen

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[AlignObject.json.zip](https://github.com/4ian/GDevelop-extensions/files/4062608/AlignObject.json.zip)

**Comment by 4ian** [comment]
Looks great! Did a few update to the description and added to extensions 👍

**Comment by grymmjack** [comment]
Thank you! It was something I thought others would love.
