### ISSUE TITLE
EscapeToExit

### ISSUE THREAD

**Issue by grymmjack** [4ian/GDevelop-extensions#31]
Allow ESCAPE key to Exit Game. Convenient, no?

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[EscapeToExit.json.zip](https://github.com/4ian/GDevelop-extensions/files/4062630/EscapeToExit.json.zip)

**Comment by 4ian** [comment]
For this one, I'm doubting if it's worth adding it as an extension as it's one condition and one action that are self describing. I would rather have extensions provide more value on top of existing actions/conditions by making more complex stuff that are encapsulated in a "simple" interface.

Does that make sense to you?

**Comment by grymmjack** [comment]
Yes it makes sense. The same thought occurred to me. It would be perhaps better as a tutorial. BTW really enjoying GDevelop! The system of extensions is beautifully implemented and very easy to follow.

**Comment by 4ian** [comment]
Happy that you like it! I think it may be needing a few improvements to reach its full potential (extensions being able to require the presence of other extensions, and behaviors being able to compose with other behaviors) - but should be already pretty useful :)

**Comment by grymmjack** [comment]
It is very useful. I am a few years user of Construct2 -> Construct3, so finding GDevelop even being a thing at all was a real gift! Very generous and I'm excited for the future of the program.
