### ISSUE TITLE
Moving Platforms

### ISSUE THREAD

**Issue by vinodsr** [4ian/GDevelop-extensions#34]
## Describe the extension
Enable Platforms  to move vertical or horizontals . Useful for jump through platforms.

Just like the platforms in mario game , upward - downward , forward - backward

This behavior can be attached to any sprite. 
## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Moving Platforms_1.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/4385714/Moving.Platforms_1.0.1.json.zip)

**Comment by Bouh** [comment]
A more complete extension for that is **SineMovement**.
It's actually available in extension list.
Thank for your time!
