### ISSUE TITLE
Drag and Drop Puzzle extensions

### ISSUE THREAD

**Issue by poly-puzzles** [4ian/GDevelop-extensions#42]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
This extension is a collection of 11 routines and one commentary section.
The commentary section describes the base puzzle, the various items contained in the scene, and where to try the puzzle.
The routines are as follows:
- processSelectedShape: determines which shape has been clicked on (even handling overlapping shapes), and sets the animation (4 static graphics per shape) accordingly. Also handles deselection of the previously selected shape. Also contains the first occurrence of my IF THEN ELSE logic.
- cursorCoordsCenterOffset: calculates the offset between the center of the shape and the location in the shape where the user clicks (used to keep the shape from "jumping" when dragging begins)
- rotateShape: handles the rotation in 90 degree increments, and ensures that the rotation does not cause all or part of the shape to pass beyond the bounds of the scene.
- flipShape: handles flipping the shape (flip vertically / flip horizontally), even if the shape has been rotated 90 or 270 degrees (see comments in function as to why this is needed)
- snapToTrayGrid: cause the shape just moved to snap to a grid, but only when the shape is in collision with the Tray object. Also checks for collisions with the border object (4 instances) and only increments the "inTray" variable if no collision exists.
- dragShapeAndKeepInScene: handles moving the object within the scene and preventing the object being dragged from passing outside of the scene border objects (2 object, 2 instances). Includes disabled logic that shows how the values of the X axis change for the mouse location vs shape location as the shape approaches, hits then tries to pass a vertical boundry.
- trayBorderCollision: causes one or more of the border instances (4 instances) to turn red if a shape is in collision with that border.
- shapeCollisions: only active when a a shape is in collision with the tray object, if the shape  object is also in collision with another shape object, the animations of both objects is set to an overlap state (yellow with black triangles). Also handles resetting the shapes to a normal state when the collision is removed.
- challangeRadioButtonClicked: based on the "radio button" clicked, sets the animation of the clicked object to selected (yellow) and changes the description text shown on in the scene
- mainMenuButtonOpacity: "dims" the puzzle function buttons (rotate and flip) when the challenge menu is visible
- resetPiecesToStartPosition: resets the puzzle to its initial configuration.

There are no behaviors in this package.

## Checklist

- [x ] Extension has a proper name and description.
- [x ] Extension has tags (for example: "platform, brick, breakable").
- [x ] All behaviors have a description.
- [x ] All functions (actions, conditions, expressions) have descriptions.
- [x ] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Finally, attach the .json file of your extension here.

[drag-and-drop-puzzle-extension.json.zip](https://github.com/4ian/GDevelop-extensions/files/4768652/drag-and-drop-puzzle-extension.json.zip)

(note GitHub does not support upload of .json files, so I compressed it via OSX)

**Comment by D8H** [comment]
Do you have an example that illustrates how to use the extension?

**Comment by arthuro555** [comment]
After taking a very quick look, it seems all function are either about snapping objects (for which we already have 2 extensions) and the rest are specific to poly.puzzles specific game. I would reject this extension as it doesn't provide anything new and/or useful.

**Comment by Bouh** [comment]
Ok I close for the moment.
The discussion can continue, if necessary another examination will be made.
Thank you for the feedbacks guys 💯
