### ISSUE TITLE
Rotate String 13 Characters Extension

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop-extensions#43]
## Describe the extension
This extension adds an action that rotates all alphabetic characters in a string by 13 characters.

By passing a string to this expression, you can go from:

- "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

to 

- "NOPQRSTUVWXYZABCDEFGHIJKLMnopqrstuvwxyzabcdefghijklm"

This can be used for basic secrets, passwords, or very insecure encryption of data.

## Checklist

- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions.
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
Since Github doesn't allow uploading of json, I've renamed it to .txt
[Rotate13.txt](https://github.com/4ian/GDevelop-extensions/files/4872433/Rotate13.txt)

**Comment by 4ian** [comment]
Looks great, thanks!

**Comment by Silver-Streak** [comment]
No clue if people will find it useful or not, but I made it and found it useful for me, so might as well share.
