### ISSUE TITLE
Mouse Cursor Extension

### ISSUE THREAD

**Issue by AlexSmart6667** [4ian/GDevelop-extensions#44]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
It makes any object selected a cursor.
## Checklist

- [x] Custom Cursor
- [x] "Cursor, pointer, objects"
- [x] there are no behaviors 
- [x] Sets the object as a sursor and hides the mouse.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Cursor.json.zip](https://github.com/4ian/GDevelop-extensions/files/4885107/Cursor.json.zip)

**Comment by Bouh** [comment]
This extension can be condensed to a single action.
![image](https://user-images.githubusercontent.com/1670670/110002614-dcf8a500-7d15-11eb-905a-1892fd67d1a6.png)
Thanks for your time on it but there is nothing more simple.
