### ISSUE TITLE
New extension - convert number to string and format to 2 decimal places

### ISSUE THREAD

**Issue by poly-puzzles** [4ian/GDevelop-extensions#45]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
This extension takes in a number value, converts it to a string and formats it to two decimal places. Any excess decimal digits due to system rounding errors (e.g. 123.5 becomes 123.50) are rounded by .05 then removed.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[formatToTwoDecimals.json.zip](https://github.com/4ian/GDevelop-extensions/files/4909848/formatToTwoDecimals.json.zip)

Finally, attach the .json file of your extension here.

**Comment by Bouh** [comment]
This kind of extension can be cool, but in a different way.

I think about these expressions for convert: 

- 123456789 to 123 456 789
- 1234.56 to 1 234,56 (comma as separator)
- 1234,56 to 1 234.56 (period as separator, used in other languages than english)
- Remove the useless zero
- Add decimal with zero


- Use the format PascalCase on names of your functions.
- Add capitals on sentences and descriptions for each functions.
- The period at the end of the descriptions
- For the timers and variables add the underscore at the beginning of the names.
**write_timer** to **_write_timer**, check the others name, for timers and variables.
This reduce the chance to overwrite an existing variable and timer used by an user.
- Add more tags. what is for your extension? Find the keywords.
- Make beautiful sentences for your extension description, this will be the first things viewed by the users.

The lastest extension accepted was **Extended math support**, you can see how the descriptions of the extension are done, it's clean.

**Comment by Bouh** [comment]
@poly-puzzles
This extension has not been updated for months. Do you want to continue working on it?
This issue will be closed in 30 days without an update.

**Comment by arthuro555** [comment]
I think they won't do the changes you suggested and the extension as it is is way too specific to really be used by anyone. I would reject this extension.

**Comment by 4ian** [comment]
Let's close now! Someone can take over it or start a new one :)
