### ISSUE TITLE
Game Save and Load Helper Utilities

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop-extensions#48]
## Describe the extension
We've seen a lot of folks on the forums and discord asking about how to save. While I have a system that I figured out for the game I'm working on, some users don't understand the screenshots or instructions on how to deal with things like Storage vs Filesystem, Structure Variables, converting to/from JSON, etc. 

This extension tries to simplify those concepts and automates some of them for the user.  While the long term goal is to add actions for both filesystem and storage saving, right now this extension allows for the following:

- Adding string data to  "GameSave" data
- Adding number value data to a "GameSave" data
- Save all GameSave data to a user defined storage location
- Load all GameSave data from a user defined storage location

## Checklist

- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions.
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
Extension file: [SaveLoadHelper.txt](https://github.com/4ian/GDevelop-extensions/files/4956978/SaveLoadHelper.txt)
JSON File saved as .txt due to GitHub limits.
Commented Example Project: 
[GameSaveUtilitiesExample.zip](https://github.com/4ian/GDevelop-extensions/files/4957047/GameSaveUtilitiesExample.zip)

Please let me know if people find this useful or not, as I consider this a "Version 0.5" right now, but didn't want to spend more time implementing the filesystem actions if it wasn't useful.

**Comment by Midhil457** [comment]
Hi, I am not sure if you are still looking to add this,

But still here are some suggestions,

- In the function "AddIntegerToSave" ToNumber(GetArgumentAsString("Data")). but I think GetArgumentAsNumber("Data") will work fine

- Adding expressions to get attributes might be better to avoid accidental changes done to the GameSave variable, and easier reading of attributes

- An icon could be added

- Having variables with __YourExtensionName_ might help reduce conflicts, http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#variable_names

:)

**Comment by Bouh** [comment]
![image](https://user-images.githubusercontent.com/1670670/122784884-26640480-d2b3-11eb-97f1-a3339bb06ebf.png)

**Comment by Bouh** [comment]
I persist to think this extension is useful.
The basic idea of the app is precisely to have a level of abstraction on code.
The structures are not complicated when you understand them, but use this extension is simpler and that's the basic idea of GD, hide the difficulty and by domino effect the syntax.

So even if this extension is a simple wrapping I think it has its place.

This raises another problem at the root of all reviews on extensions: There is a concern to evaluate the relevance of an extension that is a simple envelope or an extension that is an envelope but that really simplifies.
