### ISSUE TITLE
Blink extension

### ISSUE THREAD

**Issue by NJ-13** [4ian/GDevelop-extensions#49]
A simple extension that blinks object over entire course of time 

it can be added with any project , as it creates timer of its own before implementing on an object,This is my so kindly pardon for any mistakes

[
[Blink.zip](https://github.com/4ian/GDevelop-extensions/files/5050372/Blink.zip)

](url)

**Comment by Silver-Streak** [comment]
Hello @NJ-13, nice work on this.

Unfortunately, there's already a blink extension that flashes an object over time:

![image](https://user-images.githubusercontent.com/24237149/90322982-b2353380-df20-11ea-924d-ff9e99681009.png)

Have you tried that extension to see what's different from yours?
