### ISSUE TITLE
Constants Extension

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#50]
**⚠️ Please edit and complete this before submitting your extension:**

## Describe the extension
A collection of 13 mathematical constants used in many areas such as mathematics and geometry.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[const.zip](https://github.com/4ian/GDevelop-extensions/files/5152281/const.zip)

Finally, attach the .json file of your extension here.

You also may have to create an account on GitHub before posting.
If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by Bouh** [comment]
Hi

Thank for this extension.

- I think it's more relevant to rename this extension , like "Mathematical constants" or something similar to math. I understand the concept behind **const**, but it's not logic for everyone.

- I see there are expression already existing in GDevelop, can you remove the double?
[Here the current list in GD.](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/expressions-reference#expressions_reference)

- Texts in the description, full Name displayed in the editor functions list, and the name of the extension must start with an uppercase letter.

- In expressions you define a function, like for Euler's number, you can simplify by: 
```JS
eventsFunctionContext = Math.E;
```

- Reduce the parenthesis everywhere.
 `τ (tau) (two pi)`  to  `τ (tau, two pi)`

**Comment by Add00** [comment]
Thanks for the feedback I'll be sure to do that.

**Comment by 4ian** [comment]
> eventsFunctionContext = Math.E;

I think you forgot `.returnValue`? :) But yeah I agree, there are a lot of functions that you don't need at all. Make the code as simple as possible - in most of these case you don't need more than one line :)

**Comment by Add00** [comment]
I guess this issue can be closed since it's functionality is included in the _Extended Math Support_ extention
