### ISSUE TITLE
Extended Math Support Extension

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#56]
## Describe the extension
This extension aims to add more advance math concepts into GDevelop and some other general improvements. The extension includes; common mathematical constants (pi, e), common mathematical formulas (slope, hypotenuse), recursive functions (factorials, Fibonacci numbers) and finally, coordinate conversions for the polar and isometric systems.   

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Math.zip](https://github.com/4ian/GDevelop-extensions/files/5392382/Math.zip)

**Comment by Add00** [comment]
I forgot to state this in the main post, but this extension is an amalgamation of three previous extensions. So if anyone feels that one or some of the functions don't belong, I could remove them or spin them off to their own extension.

**Comment by Add00** [comment]
Updated descriptions
[Math.zip](https://github.com/4ian/GDevelop-extensions/files/5393379/Math.zip)

**Comment by Bouh** [comment]
Hi thank you for your work on this extension!

In the descriptions, no need to rewrite the name of the arguments.
` x1 | x value of the first point`
Can just be
` The value of the first point`

In **gcf**, "a | any interger" goes to "Any integer", but this allow to use float number too?
If no, you should check the value or format it just after _getArgument()_.

"Factorial (!)"
Unless the _(!)_ have a sense i didn't know yet, let's go without signs.

Here the new files reviewed, let me know if it's good for you, if you can plug the extension on your procedural example it will be a great test.

I've changed the name of the extension the expressions in the game need to be rewrite.
_ExtendedMath::constant("Golden_ratio)"_ 


[ExtendedMathSupport.zip](https://github.com/4ian/GDevelop-extensions/files/5393503/ExtendedMathSupport.zip)

**Comment by Add00** [comment]
Thanks for your improvements and feedback, I really like how you described the _colour_ function, it's much more understandable. 

Improvements since last time:
- I added several edge case checks to both the _lcm_ and _gcf_ expressions
- Removed the ! from factorial
- Tested it in the Procedural example and it works well (after this extension is complete I'll submit it to be an example project)

Ideas:
I was also thinking that the _colour_, _rgbToHex_ and _hexToRgb_ don't really fit in with an extension about math. Maybe they should be their own extension about colours.  

Also, should I change the default value for the _constant_ function currently it's set to -1, but that doesn't really tell the user whats wrong.

[ExtendedMathSupport.zip](https://github.com/4ian/GDevelop-extensions/files/5394620/ExtendedMathSupport.zip)

**Comment by Bouh** [comment]
> Also, should I change the default value for the _constant_ function currently it's set to -1, but that doesn't really tell the user whats wrong.

The default number value return by default in GD is 0.

> I was also thinking that the _colour_, _rgbToHex_ and _hexToRgb_ don't really fit in with an extension about math. Maybe they should be their own extension about colours.

This make sense to me.

**Comment by Add00** [comment]
I took out the _colour_ related functions and changed the default value of _constant_ to zero. 

[ExtendedMathSupport.zip](https://github.com/4ian/GDevelop-extensions/files/5394756/ExtendedMathSupport.zip)

**Comment by Bouh** [comment]
Great! Let me review the file one last time today :)
