### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by Daniel-172** [4ian/GDevelop-extensions#6]
## Describe the extension
Function: health bar system, which replaces the following conditions and actions:
</br>
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360428-5c252d80-7e4e-11e9-87ec-d1bbf5f4d6ca.png)
</br>
</br>

It is important to create a variable with the name life to store the value of life, if you are going to change the name the variable is important also to do it in the configuration of the function as shown in the image:
</br>
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360447-7828cf00-7e4e-11e9-9c90-377ed6e76b09.png)
</br>
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360650-86c3b600-7e4f-11e9-8503-f33060044555.png)
</br>
</br>
it is also important to put the width of the spr to the value of the variable or vice versa
</br>
</br>

<b> <H2>screenshots </H2></b>
</br>
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360675-afe44680-7e4f-11e9-9773-fce80ed3c65c.png)
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360682-b96dae80-7e4f-11e9-9e80-02b6cce1a2a6.png)
</br>
![imagen](https://user-images.githubusercontent.com/28544563/58360691-c7bbca80-7e4f-11e9-8538-528125105b2e.png)

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Health Bar.zip](https://github.com/4ian/GDevelop-extensions/files/3218839/Health.Bar.zip)

**Comment by arthuro555** [comment]
Sorry for the late and negative answer: I am afraid this extension will have to be rejected, as it is way too specific and unflexible.

**Comment by Bouh** [comment]
I agree it's not flexible as you said.
I think another new extension can do the trick, with a Shape painter object as a requirement the Health Bar can be added on an object with behavior or with action on instances.
And this way all the variables remain internally to the extension.
