### ISSUE TITLE
Extension: CreateGridOfObjects

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#60]
## Describe the extension
Create a grid made of multiple copies of an object.  Select the object, choose the number of rows and columns, the spacing between objects, and the starting point. 

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[CreateGridOfObjects.zip](https://github.com/4ian/GDevelop-extensions/files/5405560/CreateGridOfObjects.zip)

**Comment by 4ian** [comment]
Thanks for submitting this :) 
I've seen there was some computations done at the beginning of the scene. Could this be moved to be done whenever the action is called? 
Also, will this work if I use the action for more than one object?

**Comment by tristanbob** [comment]
@4ian, it's an honor to speak with you.  My programming skills are very basic; I would never have built a game without Gdevelop (it's wonderful). 

To answer your questions:

1) I've seen there were some computations done at the beginning of the scene. Could this be moved to be done whenever the action is called? 

Yes, I will make it so that they are triggered once, but it does not have to be at the beginning of a scene.

2) Also, will this work if I use the action for more than one object?

You can call this function multiple times, using different objects.  But currently, only one object can be used.  As a work-around, with different spacing and starting points, you can make a grid composed of different objects.

What is your use case so that I can try to understand how I can improve?

**Comment by 4ian** [comment]
> You can call this function multiple times, using different objects.

That was the use case I had in mind :) So all good!

I think this is almost ready! A last small thing before adding this to the list of extensions:
- I guess this action is supposed to be called once in a row (like, you would probably call it at the start of the scene or with a Trigger Once condition). I think we can remove the "Trigger Once" in the first two events, they are not needed and will be executed when the action is called.

Give it a try and let me know, then I can add the extension to the registry. Thanks!

>  I would never have built a game without Gdevelop (it's wonderful).

Happy that GDevelop is useful :)

**Comment by tristanbob** [comment]
> * I guess this action is supposed to be called once in a row (like, you would probably call it at the start of the scene or with a Trigger Once condition). I think we can remove the "Trigger Once" in the first two events, they are not needed and will be executed when the action is called.

You are right, the extension works properly without "Trigger Once".  (I have a hard time knowing when I do or don't need that)

Also, after trying to explain this extension to a few people, I decided to rename it and add better descriptions.  I feel this wording makes it more simple to understand.  (Of course, you have my permission to change the wording and name it however you want.)

Extension:
CreateMultipleCopiesOfObject

Full Name:
Create multiple copies of an object

Description:
Create multiple copies of an object.  Select the object, choose the number of rows and columns, the spacing between rows and columns, and the top left starting point. 

[CreateMultipleCopiesOfObject-0.1.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/5430252/CreateMultipleCopiesOfObject-0.1.0.json.zip)

Lastly, do you think this function would make sense to be listed as a default action when you select an object?  It could go right below "Create an object".

**Comment by tristanbob** [comment]
Fixed a typo.

[CreateMultipleCopiesOfObject-0.1.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5431765/CreateMultipleCopiesOfObject-0.1.1.json.zip)

**Comment by 4ian** [comment]
Looks great! It's added to the list of extensions now 👍👍

Thanks a lot for submitting this, it's well made and will be very useful 🚀

**Comment by tristanbob** [comment]
@4ian - I want to add some object variables to the created objects that will allow people to manipulate those objects after creation.

**New Object Variables:**

RowID: 1,2,3,...n = What row does this object reside?
ColumnID: 1,2,3,....n = What column does this object reside?
CreationID: 1,2,3,...n = Starting top-left, and proceeding left to right, what order was this object created?
BatchID:  <optional parameter added by user> = Used to manage objects that were created using this function multiple times

I already use the CreationID for my SelectLevel scene, which automatically changes the text to match the CreationID, and then I let users select objects where "CreationID <= MaxLevelReached".

You could use RowID/ColumnID to selectively change (color, position, delete, etc) an entire row, a subset of rows, even/odd, random, or some other logic.

You could use BatchID to selectively change an entire batch of objects, assuming the user calls this function multiple times. 

Do you have any suggestions before I start coding this?  Do you want me to create a new issue to track this change?

**Comment by tristanbob** [comment]
Here is the extension with these 4 new object variables added:

[CreateMultipleCopiesOfObject-0.2.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/5459399/CreateMultipleCopiesOfObject-0.2.0.json.zip)

**Comment by tristanbob** [comment]
Ok, here is the file.  I have also updated all the descriptions.

[CreateMultipleCopiesOfObject-0.2.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5459601/CreateMultipleCopiesOfObject-0.2.1.json.zip)
