### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by westboy31** [4ian/GDevelop-extensions#61]
## Describtion
This extention simulate typing text , just enter text and play the action auto typing .

* Apply auto typing action to a text object to start typing and chose interval between characters .
* It automatically auto type again when the text content changes  ( but don't forget to trigger once ) .
* In condition you can catch the event typing end .
* You can also make pause to text typing and resume it after .

Extention useful for dialogue scene or in visual novel  .

## Checklist

- [*] Extension has a proper name and description.
- [*] Extension has tags (for example: "platform, brick, breakable").
- [*] All functions (actions, conditions, expressions) have descriptions.
- [*] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file :
[AutoTyping.zip](https://github.com/4ian/GDevelop-extensions/files/5447242/AutoTyping.zip)

**Comment by Bouh** [comment]
I don't see how to use it, can you forward an example with it ?

**Comment by Bouh** [comment]
- Use the format PascalCase on names of your functions.
- Add capitals on sentences and descriptions for each functions.
- The period at the end of the descriptions
- For the timers and variables add the underscore at the beginning of the names.
**write_timer** to **_write_timer**, check the others name, for timers and variables.
This reduce the chance to overwrite an existing variable and timer used by an user.
- Add more tags. what is for your extension? Find the keywords.
- Make beautiful sentences for your extension description, this will be the first things viewed by the users.

The lastest extension accepted was **Extended math support**, you can see how the descriptions of the extension are done, it's clean.

**Comment by westboy31** [comment]
done

**Comment by Bouh** [comment]
Awesome, very simple to use!
You think it's possible to support BBtext too?

In **_write_i** what is **i**? I guess it's similar to i (index) in a loop? i for instance or it's the number of characters in the word? If you can find a better name :)

Also you can reduce the two sub event from the third event in AutoTyping., jsut move the action in the third event ;)

**Comment by westboy31** [comment]
yes it's could work with bbtext i tried it , but to work with both of bbtext and textObject it's possible but user have to chose to fill one parameter fields and leave empty the other , and I don't see any other solution than making the same code for both of them . (personally i use textObject for most of games that i did , i don't khow if this is the same case for all).

in _write_i you got it , it's for index , so it's could be named "_write_index" maybe .

and for AutoTyping , i think you mean second event , and yes it's a good remark .

**Comment by Bouh** [comment]
> yes it's could work with bbtext i tried it , but to work with both of bbtext and textObject it's possible but user have to chose to fill one parameter fields and leave empty the other , and I don't see any other solution than making the same code for both of them . (personally i use textObject for most of games that i did , i don't khow if this is the same case for all).

Duplicate the function action and change the type to BBtext should be enough. Have you tested?

**Comment by westboy31** [comment]
I renamed _write_i to _write_index , delete useless sub-event , and make both of autoTyping for BBtext and for textObject accessable to download

**Comment by Bouh** [comment]
We can have only one Auto typing  extension for Text object and BBText object.

The all functions execpt AutoTyping, change the Object type to **Any object**.
You can do that because you don't use the actions or conditions specific to a BBtext or a Text objects.

For the function AutoTyping you need have two functions, one for Text and one for BBtext.
Let's call them, **Text_AutoTyping** and **BBText_AutoTyping**.

Think to add capitals on description in the parameters too.
Check everywhere for remove the space before dot.

The extension is soon ready!

**Comment by 4ian** [comment]
Thanks @westboy31 and @Bouh, this looks like a really cool extension! Looking forward to have it ready :)

**Comment by westboy31** [comment]
> We can have only one Auto typing extension for Text object and BBText object.
> 
> The all functions execpt AutoTyping, change the Object type to **Any object**.
> You can do that because you don't use the actions or conditions specific to a BBtext or a Text objects.
> 
> For the function AutoTyping you need have two functions, one for Text and one for BBtext.
> Let's call them, **Text_AutoTyping** and **BBText_AutoTyping**.
> 
> Think to add capitals on description in the parameters too.
> Check everywhere for remove the space before dot, and there is also two spaces sometimes in the sentences. (Extension description and sentences from functions.)
> 
> The extension is soon ready!

normally it is done

**Comment by 4ian** [comment]
I've posted quite a few comments in https://github.com/4ian/GDevelop-extensions/pull/62 - @westboy31 maybe you want to look at them?
