### ISSUE TITLE
Updated CreateMultipleCopiesOfObject to provide object variables 

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#64]
@4ian - I want to add some object variables to the created objects that will allow people to manipulate those objects after creation.

**New Object Variables:**

RowID: 1,2,3,...n = What row does this object reside?
ColumnID: 1,2,3,....n = What column does this object reside?
CreationID: 1,2,3,...n = Starting top-left, and proceeding left to right, what order was this object created?
BatchID:  An optional parameter added by user, used to manage all objects that were created from each call of this function

I already use the CreationID for my SelectLevel scene, which automatically changes the text to match the CreationID, and then I let users select objects where "CreationID <= MaxLevelReached".

You could use RowID/ColumnID to selectively change (color, position, delete, etc) an entire row, a subset of rows, even/odd, random, or some other logic.

[CreateMultipleCopiesOfObject-0.2.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5459601/CreateMultipleCopiesOfObject-0.2.1.json.zip)

_Originally posted by @tristanbob in https://github.com/4ian/GDevelop-extensions/issues/60#issuecomment-718800176_

**Comment by 4ian** [comment]
Published 👍 I tweaked a few descriptions and sentences.
Thanks for adding this!
