### ISSUE TITLE
Create Shadow Clones (new extension)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#66]
## Describe the extension
Create shadow clone objects that follow the same path as a primary object.  Select the primary object, the shadow clone object, the number of shadow clones, the number of frames between shadow clones, the rate that shadow clones will fade away (if desired), the Z-value of the shadow clones, and the layer the shadow clones will be created on.

This extension can be used to:
- Make an object look faster, such as during a speed powerup.  
- Give a 3D-like feel to a character
- Implement unique time-based elements, like teleporting a character back to a previous location
- Simulate the movement of a caterpillar or slinky
- Recreate games like snake or tron

These object variables can be use to manage the shadow clones:
- ShadowCloneOrder = Shadow clone identifier, where 1 is the shadow clone closest to the primary object
- FramesBehindPrimary = The number of frames that the shadow clone is behind the primary object
- ShadowCloneGroupID = Shared identifier for the shadow clones that were created (Optional)

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[CreateShadowClonesExtension-0.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5544046/CreateShadowClonesExtension-0.0.1.json.zip)

**Comment by 4ian** [comment]
Looks nice! Easy to use :) 
Do you think there would be a way to make it work for multiple objects? I've seen some Trigger Once so I think it would only work for a single object at a time?

**Comment by tristanbob** [comment]
Great question.  You are right, this extension currently works only with one primary object.  I think it might be possible to use it on multiple primary objects, but I'll have to do a lot of thinking.  I'll write back with my results.

**Comment by tristanbob** [comment]
I also want to add the ability to increase/decrease the shadows.  I am making a game similar to the hungry caterpillar book; each time he eats, he grows one more shadow clone.

**Comment by 4ian** [comment]
Both would be interesting! Flexibility of using it on multiple objects is I think important to avoid confusing/frustrating people that would want more than one object casting these shadow clones :) 
Let me know if you can get something working. Instead of Trigger Once, you might have to work with variables set on the object(s), and possibly add some "For Each Object" events so that you're sure you're handling each object separately :)

**Comment by tristanbob** [comment]
Another idea to consider:

- Give users the option to make ShadowClones use the same animation ID and frame ID that the primary object was using
- Pause animation on ShadowClones (I think they should act frozen in time, and stay in the state they were created at)

**Comment by 4ian** [comment]
That's possible indeed! That's assuming you use a sprite as the object to follow. Could be a variant (as another action) maybe, so you could use both?

**Comment by tristanbob** [comment]
Thanks to much-appreciated help from @entropy, we have made some updates to this extension:

- Moved position history under the primary object
- You can now use this extension on multiple primary objects (YES!)
-- If you want to use the same shadow clone object on both primary objects, then you must specify a unique "ShadowCloneGroupID"
- Increasing and decreasing shadow clones works... sort of.  If you try to add and remove multiple times, gaps in the shadow clone chain begin to appear.  (This bug needs resolved)

[CreateShadowClonesExtension-0.0.1_3.json.zip](https://github.com/4ian/GDevelop-extensions/files/5657105/CreateShadowClonesExtension-0.0.1_3.json.zip)

**Comment by 4ian** [comment]
Thanks! I've been very busy these days but I'll take a look and add it 👍

**Comment by 4ian** [comment]
> You can now use this extension on multiple primary objects (YES!)

Nice :) 

It seems the "empty frames" between shadows might be buggy:
I've added it to the platformer example:
![image](https://user-images.githubusercontent.com/1280130/101686171-fbc60300-3a68-11eb-8963-34543f5cf4ed.png)

and the result seems to be a single shadow clone (the others have been skipped?): 
![image](https://user-images.githubusercontent.com/1280130/101686259-18fad180-3a69-11eb-80ae-41d19fe2d9ca.png)

On the description side of the action, this part is useful in the extension description but should not be in the action description:
![image](https://user-images.githubusercontent.com/1280130/101686330-329c1900-3a69-11eb-88b4-8b025f41bd37.png)

as it's taking place and the creator already made the choice of using the extension - so they know the utility.

Finally, I would also rename the action slightly to make it clear that this is an action that must be called continuously to work properly. Something like "Animate" might be better suited (while "create" looks like you just need to call this action once, and then you can forget about it).

![image](https://user-images.githubusercontent.com/1280130/101686557-8444a380-3a69-11eb-8d3f-36649917f805.png)
![image](https://user-images.githubusercontent.com/1280130/101686586-8dce0b80-3a69-11eb-9c0e-e268fe6d71bf.png)

Remember that you also have a Trigger Once that will probably give very weird result/bugs because you can use this action on more than one object:
![image](https://user-images.githubusercontent.com/1280130/101687210-717e9e80-3a6a-11eb-9d73-5621334ef924.png)

I recommend using a variable to simulate a Trigger Once. You could actually maybe store a "CreatedShadowNumber" - which is 0 by default, and then that you increment/decrement (instead of a `c` variable) :)

**Comment by tristanbob** [comment]
If possible, I'd like to work on it more before publishing.  I am using this issue as a way to share my code and get feedback (and code improvements) from others.   I don't see a way for me to tag this with something like "in progress" and eventually "submitted for approval".

**Comment by 4ian** [comment]
I've made a Work In Progress label ;) Tag me when you have a new version :)

**Comment by tristanbob** [comment]
FYI - The problem with your test is that you are fading opacity by 20 every frame, and you have 10 frames between coins, so the next shadow will be faded by 200.  :)

**Comment by tristanbob** [comment]
Speaking of that, I should change the logic so that it fades opacity "per shadow" and not "per frame"....

**Comment by 4ian** [comment]
Ah I see! Works well when I change that then. But yeah I think per shadow would be awesome then, especially when using a large number of frames between shadows :)

**Comment by tristanbob** [comment]
I have changed the opacity fade to per clone instead of per frame. 

I’m also going to try turning this into a behavior and see if it works better.

**Comment by 4ian** [comment]
Nice! Let me know when you have a new version.

**Comment by tristanbob** [comment]
## Version 0.3.3

Changes include:
- Fixed bug when adding and removing clones
- Cleans up unused history (when the number of clones goes down)
- Now mimics the angle, scale, animation, and frame of the primary object
- Works with multiple instances of a primary object
- Opacity fade is per clone (instead of per frame)
- Removed an extra ForEach() loop 
- Tested with an example game

@4ian I am ready for you to review this for inclusion into GDevelop.  Feel free to send more of those delicious nit-picking recommendations you often provide!  :)

## Live Demo

https://games.gdevelop-app.com/game-9281a1a6-15f3-4c7c-8267-07642cce765a/index.html

## Example Game

[ShadowClonesExample.zip](https://github.com/4ian/GDevelop-extensions/files/5985886/ShadowClonesExample.zip)

## Video

https://user-images.githubusercontent.com/8879811/108014809-f2f32f80-6fcb-11eb-872d-231334eb015c.mp4

## Extension file

[ShadowClonesExtension_0.3.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/5985917/ShadowClonesExtension_0.3.3.json.zip)

**Comment by tristanbob** [comment]
I woke up this morning and realized that I didn't test an animated sprite.  I think I forgot to Pause the animation of the shadow clones.  

Don't import this until I review it later tonight.

**Comment by 4ian** [comment]
Sure let me know when it's ready. Looks really good! 👍

**Comment by tristanbob** [comment]
## Version 0.3.4
Changes include:

- Paused the animation of shadow clones
- Tested with an example game (now with sprites)

## Live Demo
https://games.gdevelop-app.com/game-9281a1a6-15f3-4c7c-8267-07642cce765a/index.html

## Extension file

[ShadowClonesExtension_0.3.4.json.zip](https://github.com/4ian/GDevelop-extensions/files/5993384/ShadowClonesExtension_0.3.4.json.zip)

## Video

https://user-images.githubusercontent.com/8879811/108159537-75e7b900-70a4-11eb-9648-8370549aab5b.mp4

**Comment by 4ian** [comment]
Looks very good! 👍👍

Is there a need to store both width/height and scale x/y? Width/height should be linked to the scale anyway?

Nitpicking: instead of inverting these conditions:
![image](https://user-images.githubusercontent.com/1280130/108250324-688b0700-7156-11eb-8994-ea1d54a7bd23.png)

You can use the "not equal" operator?

Finally maybe mention in the description that the shadow will be virtually linked to the primary object (so one should not try to use the "Linked objects" feature between the shadows and primary object, otherwise they risk breaking the shadows).

**Comment by 4ian** [comment]
Apart from that we should be good to go :) Because this is mostly nitpickings/not that important, I'll go ahead and add the extension now :) 

I would also recommend changing "Create _PARAM3_ copies of _PARAM2_ that follow the position..." to "Create and animate _PARAM3_ copies of _PARAM2_ that follow the position" to make it a bit clearer that this is not a one off action, it must be called at every frame.

**Comment by tristanbob** [comment]
> Is there a need to store both width/height and scale x/y? Width/height should be linked to the scale anyway?

I wasn't sure the best thing to do.  If I am setting both scale AND width/height, then the actual size will only be affected by the last action performed, right?  I think I will probably remove width/height and just use the scale.

> Nitpicking: instead of inverting these conditions:
> ![image](https://user-images.githubusercontent.com/1280130/108250324-688b0700-7156-11eb-8994-ea1d54a7bd23.png)
> 
> You can use the "not equal" operator?

Since these have the same logic, I like to think that the big red invert on the left is easier to see than the difference between "=" and "!=".  I'm certainly willing to change, if you recommend using "!=".

> Finally maybe mention in the description that the shadow will be virtually linked to the primary object (so one should not try to use the "Linked objects" feature between the shadows and primary object, otherwise they risk breaking the shadows).

This extension DOES link the shadow objects to the primary object.  I actually think users will need to use the linked conditions/actions if they want to delete shadow clones of a single primary object.   This extension does provide a "DeleteShadowClones" action that will delete all shadow clones with the same ShadowCloneGroupID, but I don't think users will have unique ShadowCloneGroupID for each instance.

Lastly, I think my next version will include boolean variables that let the user decide which properties of the primary object should be used on the shadow clones.  For instance, if you want small objects (dust-trail/foot-prints/pets/minions) to follow your player, this extension will currently force the width/height of the shadow clones to match the player.

**Comment by tristanbob** [comment]
> Apart from that we should be good to go :) Because this is mostly nitpickings/not that important, I'll go ahead and add the extension now :)
> 
> I would also recommend changing "Create _PARAM3_ copies of _PARAM2_ that follow the position..." to "Create and animate _PARAM3_ copies of _PARAM2_ that follow the position" to make it a bit clearer that this is not a one off action, it must be called at every frame.

I will add this to the Trello board to change on the next version.

**Comment by 4ian** [comment]
> Lastly, I think my next version will include boolean variables that let the user decide which properties of the primary object should be used on the shadow clones. For instance, if you want small objects (dust-trail/foot-prints/pets/minions) to follow your player, this extension will currently force the width/height of the shadow clones to match the player.

Yes great idea, not everyone may want to have the shadow clones to use the same width/height :) Giving the choice here is surely a good idea

**Comment by tristanbob** [comment]
## Version 0.3.5

Changes include:

- Added boolean variables to let users choose which primary object properties will be matched on the shadow clones.
- Changed DeleteShadowClones function.  It now deletes shadow clone instances that are linked to the primary object instance.
- Changed all single-character variable names to descriptive names
- Changed wording based on recommendations

## Live Demo
https://games.gdevelop-app.com/game-82269a54-55e7-4f19-87c2-26e3e30dd8aa/index.html

## Extension file

[ShadowClonesExtension_0.3.5.json.zip](https://github.com/4ian/GDevelop-extensions/files/6000436/ShadowClonesExtension_0.3.5.json.zip)

**Comment by 4ian** [comment]
Updated! Thanks :)

**Comment by tristanbob** [comment]
## Version 0.3.6

Changes include:
- Reset PrimaryObject variables when DeleteShadowClones function is executed (needed for dash to work)
- Added link to Youtube video tutorial on how to use the extension (https://youtu.be/2t4ANYgrrak)
- Added link to Entropy's Youtube channel in the credit field

Unrelated changes to platformer example:  (FYI - I'll submit this separately)
- Added horizontal dash (press "x") with shadow clones
- Added instructions on controls (I'm not sure how translations are done)
- Added animation to checkpoint cactus (y-scale tween) and added sound
- Added victory trophy

## Live Demo
Platformer example with Dash added (press "x" to dash)
https://games.gdevelop-app.com/game-0a3741e9-22dc-44d6-bdef-c0647e85fbd6/index.html

## File
[ShadowClonesExtension_0.3.6.json.zip](https://github.com/4ian/GDevelop-extensions/files/6056340/ShadowClonesExtension_0.3.6.json.zip)

**Comment by 4ian** [comment]
Updated, thanks! 👍

**Comment by Zimquadery** [comment]
[Shadow clone.zip](https://github.com/4ian/GDevelop-extensions/files/6164654/Shadow.clone.zip)
Added "scale down per clone" action to the fanction.

**Comment by tristanbob** [comment]
Zim Quadery thanks for sharing this!  I looked at it briefly, and it looks good.  I think I even learned that I can remove the opacity setting on every frame and just do it once as you did for scale.

I'll test that change and combine it with yours, and submit it as a minor update to this issue.

**Comment by tristanbob** [comment]
I have almost completed a major overhaul of ShadowClones that is much simpler and more resilient.  (I'll provide more details in a later post).  

I have one remaining problem that I am hoping someone could look at.  (If you were confused how ShadowClones worked in the past, it should now be much easier to understand)

Problem:
- ShadowClones are being created even when there is no position data. 

I have a condition that is supposed to only create them only if the X OR Y position are not 0.  However, these objects are being created with x=0 AND y=0.   (Note: You can't see them because scale values are also 0, but you can see in the debugger).

![Screenshot 2021-05-24 094117](https://user-images.githubusercontent.com/8879811/119376663-6ff00e00-bc79-11eb-81a8-385b72348c89.jpg)

## Extension file
[ShadowClonesExtension_0.5.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/6533642/ShadowClonesExtension_0.5.0.json.zip)

## Source Files
[ShadowClonesExample_SourceFiles_0.5.0.zip](https://github.com/4ian/GDevelop-extensions/files/6533639/ShadowClonesExample_SourceFiles_0.5.0.zip)

## Game Example
https://games.gdevelop-app.com/game-dd9b3439-cf8d-46c3-abdf-211425e808e7/index.html

**Comment by tristanbob** [comment]
## Version 0.5.1

Updates:
- Revamped logic to increase simplicity, resiliency, and efficiency (while functionality for the user remains the same)
- Added the ability to shrink the size of clones (this acts similar to opacity fade)
- Fixed bug where hundreds of clones could be created on top of each other when changing the number of clones
- Changing the distance between clones now moves them instead of deleting and recreating

Future optimization:
- Only create shadow clones when there is position history for them. 
(I have a condition that is supposed to enforce this, but it is not working.  Shadow clones are created even if there is no position history and moved to x=0,y=0 with scale=0.  If anyone has a solution to this, please let me know! In the meantime, this update is a major improvement to the existing version of ShadowClones).

## Example game
https://victrisgames.itch.io/shadowclones-extension-demo

## Extension file
[ShadowClonesExtension_0.5.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/6572443/ShadowClonesExtension_0.5.1.json.zip)

**Comment by 4ian** [comment]
Nice! This seems good to go even without the further optimization? 

>  Shadow clones are created even if there is no position history

Could you explain exactly what this means?
Do you use a structure?

> https://victrisgames.itch.io/shadowclones-extension-demo

Very nice! I think these demos are very good candidates for the new repository of examples https://github.com/GDevelopApp/GDevelop-examples :) 
So that they will be surface directly in (the next version of) GDevelop. And they will also list the extensions used in them.

**Comment by tristanbob** [comment]
Yes, I use structure variables.  On every frame, I create a new child variable under "PrimaryObject.ObjectHistory".  So the 3 most recent frames would be:

PrimaryObject.ObjectHistory.1
PrimaryObject.ObjectHistory.2
PrimaryObject.ObjectHistory.3

I store all the characteristics of the PrimaryObject as child variables under each frame.  For instance, the most recent frame has:

PrimaryObject.ObjectHistory.1.xpos
PrimaryObject.ObjectHistory.1.ypos
PrimaryObject.ObjectHistory.1.angle
PrimaryObject.ObjectHistory.1.animation
PrimaryObject.ObjectHistory.1.frame
PrimaryObject.ObjectHistory.1.xscale
PrimaryObject.ObjectHistory.1.yscale
PrimaryObject.ObjectHistory.1.width
PrimaryObject.ObjectHistory.1.height

Lastly, on every frame I move the data one frame down so that the most recent data always lives at "PrimaryObject.ObjectHistory.1".  (BTW, I also "clean-up" extra frame data so I only keep the exact number I need.)

The missing optimization is that this extension currently creates all requested ShadowClones in the first frame.  Clones are created at the current position of the PrimaryObject, but I immediately move them to the values stored in the ObjectHistory structure.  Since this structure has not been populated with data yet, the clones are moved to x=0,y=0.  If you have enabled matching scale, you will not see them because their scale is also 0.  These objects do exist, and you can see them in the debugger.  

I have conditions that should only create the objects when there is position data in ObjectHistory for their frame, but for some reason, they are not working... 

**UPDATE:**  Thanks to the benefit of explaining a problem to someone, I found the error in my code.  My conditions were supposed to check for the frame number, but I was only checking the clone number.  Thanks for pushing me on this, @4ian.  :)

Here are the fixed conditions:
 
![Screenshot 2021-05-31 213433](https://user-images.githubusercontent.com/8879811/120263157-5e4dce00-c258-11eb-8745-0a82ae6fcd0d.jpg)

## Version 0.5.2

- Add optimization so that shadow clones are now only created when there is object history for their frame.

## Extension file

[ShadowClonesExtension_0.5.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/6573184/ShadowClonesExtension_0.5.2.json.zip)

**Comment by 4ian** [comment]
Amazing! Good catch :) 
I've updated the extension 👍

Also note that this kind of manipulation can be easier to do in the future thanks to arrays (just for the fact of being able to use numbers in the brackets: `ObjectHistory[...]`). We may add some array manipulation actions to "pop"/shift an element from the beginning of the array :)
