### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by achubutkin** [4ian/GDevelop-extensions#68]
## Describe the extension
Extension for connecting SDK Yandex.Games (https://yandex.ru/games/docs/). The extension provides the following features:
integration of ad display (full-screen banner, rewarded ad);
automatic switch to full screen mode;
setting the screen orientation at the start of the game;

## Checklist

- Extension has a proper name and description.
- Extension has tags (for example: "platform, brick, breakable").
- All behaviors have a description.
- All functions (actions, conditions, expressions) have descriptions.

[YaGamesSDK_Extension.zip](https://github.com/4ian/GDevelop-extensions/files/5579162/YaGamesSDK_Extension.zip)

I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

Finally, attach the .json file of your extension here.

You also may have to create an account on GitHub before posting.
If your extension is high quality and useful, it will be added to the list of GDevelop community extensions.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by 4ian** [comment]
Nice :) 

I've made a few fixes:
- Don't use `_variables`, or anything that has an underscore. It's private and will break in the future. Instead, use `getVariables()`.
- Careful about the indentation of your code, it's cleaner when all brackets are properly indented and much quicker to understand.
- I've added support for the next version of GDevelop to use "booleans" (True/False or Yes/No) parameters, so I've changed the extension to use them for the parameters of the action to initialize the SDK.

I've published it, thanks again! 👍

**Comment by arthuro555** [comment]
> Careful about the indentation of your code, it's cleaner when all brackets are properly indented and much quicker to understand.

Little tip: you can type ctrl-shift-f to let Monaco reindent the code for you.

> I've added support for the next version of GDevelop to use "booleans" (True/False or Yes/No) 

I can't seem to find that commit on the GDevelop repository 🤔 did you already push it?

**Comment by 4ian** [comment]
It's here :) https://github.com/4ian/GDevelop-extensions/commit/2d45c763c2c120cdc6c6394c875b8fa95e78bce5

> Little tip: you can type ctrl-shift-f to let Monaco reindent the code for you.

Nice! I did not know about this :)

**Comment by arthuro555** [comment]
I meant the commit to pass booleans as functions parameter on the main GDevelop repository

**Comment by 4ian** [comment]
Oops forgot to push it 😄 It's here: https://github.com/4ian/GDevelop/commit/a0e0fdf6e1cfe965dff9fb976d135bd8c9517716
