### ISSUE TITLE
YSort

### ISSUE THREAD

**Issue by GustavoMarciano** [4ian/GDevelop-extensions#7]
## The extension
Create an illusion of depth based on the Y position of the object ,useful for isometric games.
![YSort](https://user-images.githubusercontent.com/23220658/58442761-da3e3a00-80c3-11e9-8007-4b0a60791bb0.gif)

## Checklist
- [X]  Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

[YSort.zip](https://github.com/4ian/GDevelop-extensions/files/3227562/YSort.zip)

**Comment by 4ian** [comment]
Thanks for submitting this :)

Can you update a few things:

> Attention the origin point of the object will be used as parameter

This is not clear, could you rewrite this? "The origin point of the object is used to determine the depth".

> its y position

its Y position

> create an illusion of depth base [...]

Create an illusion of depth based [...]

> the object ,very handy for isometric games

the object. Useful for isometric games.

It's important to have no typo/mistakes and to be very clear as dozens of thousands of users will see this, including in a professional context.

**Comment by GustavoMarciano** [comment]
done

**Comment by 4ian** [comment]
I've made some more modifications to descriptions to add examples and fix typos (no space before comma, etc...)

Merged in the extensions! :) Thanks for submitting it :)
