### ISSUE TITLE
CreateMultipleCopiesOfObject version 0.2.2 (update)

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#71]
Updating this extension:

- Change all scene variable names to be prepended with `"__CreateMultipleCopiesOfObject_"`

- Change all object variable names to be prepended with `"__CreateMultipleCopiesOfObject_"` 
(This will break anyone who uses these.  Do you think we should keep the prepend?

- Added the ability to specify which layer the objects will be created on, and also the Z order of the objects.

- Updated descriptions to include new parameters and object variable names

[CreateMultipleCopiesOfObject-0.2.2.json.zip](https://github.com/4ian/GDevelop-extensions/files/5611392/CreateMultipleCopiesOfObject-0.2.2.json.zip)

**Comment by 4ian** [comment]
> This will break anyone who uses these. Do you think we should keep the prepend

For scene variable name yes but for object variable names no. This is because the extension makes it clear, in the description, that some object variables will be set. As they are useful for the user, they should have a short name without a complex prefix. In the worst case, if someone does not want them, they can always change their value :) 

> Added the ability to specify which layer the objects will be created on, and also the Z order of the objects.

👍

**Comment by tristanbob** [comment]
Good input, @4ian.  I have rolled back the changes to the object variables (and I fixed a regression bug from my last change).

[CreateMultipleCopiesOfObject-0.2.3.json.zip](https://github.com/4ian/GDevelop-extensions/files/5653913/CreateMultipleCopiesOfObject-0.2.3.json.zip)

**Comment by 4ian** [comment]
Updated (a01f87a642df427e2bfa7dd5dc40a7cac2539e1d)! Thanks 👍

**Comment by tristanbob** [comment]
I just tested the version you pushed, and it works great!

**Comment by tristanbob** [comment]
Here is a tutorial I made that uses this extension several times to generate environmental objects (border walls, asteroids, items to collect):

https://youtu.be/rlGSlNSRR9w

**Comment by 4ian** [comment]
Nice, I've added a link to it in the extension description :)
