### ISSUE TITLE
New extension: "TravelToRandomPositions"

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#74]
## Describe the extension

Object will select a random nearby location and begin moving towards it (using the Pathfinding behavior). 
Once the object reaches a destination, it will select a new random location and begin moving towards it.

If you want to modify the speed of the object, edit the Pathfinding behavior of the object.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[TravelToRandomPositions-0.0.1.json.zip](https://github.com/4ian/GDevelop-extensions/files/5655159/TravelToRandomPositions-0.0.1.json.zip)

**Comment by tristanbob** [comment]
Update: v0.2.0

Add the ability for users to select a Min value for distance to the next position. 

`Move _PARAM1_ to random positions, where each stop is at least _PARAM3_px and at most _PARAM4_px from the current position.`

[TravelToRandomPositions-0.2.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/5655536/TravelToRandomPositions-0.2.0.json.zip)

**Comment by 4ian** [comment]
Looks great 👍 Added to the list of extensions. Thanks! 

This make me think that later it would be great to have behaviors that can require other behaviors to be installed on an object.

**Comment by tristanbob** [comment]
It looks like you uploaded the 0.0.1 version, not the 0.2.0?

**Comment by tristanbob** [comment]
And to your point, I started by trying to make this a behavior, but we need the ability to use actions from other behaviors (similar to how stand-alone functions do this).

**Comment by 4ian** [comment]
Fixed! Thanks for catching this :)

**Comment by tristanbob** [comment]
I tested the version you just pushed, and it's working great.  Thanks!
