### ISSUE TITLE
Toggle value extension

### ISSUE THREAD

**Issue by Entr0py404** [4ian/GDevelop-extensions#78]
This extension toggles values (0-1, yes/no, true/false)
and can be used for things like muting sounds and music.

Would help in situations like this one:
![102002078-42f50380-3cb6-11eb-836f-dfd78df05bda](https://user-images.githubusercontent.com/75917656/102019171-2a74ff80-3d2f-11eb-87d1-159425ad37d6.jpg)

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

Extension file:
[ToggleValue.zip](https://github.com/4ian/GDevelop-extensions/files/5684108/ToggleValue.zip)

I cannot confirm MIT license for the sound use in the example and should not be used as an official example
Example project:
[Toggle.zip](https://github.com/4ian/GDevelop-extensions/files/5684112/Toggle.zip)

**Comment by 4ian** [comment]
Thanks for submitting this :)

A few questions:
- What is EXT_ElseToogle useful for?
- You can probably set the return value to a default value always, then use a single condition to set it to the other value otherwise.
- What do you think is the best word: "Toggle", "Switch", "Flip"?

**Comment by Entr0py404** [comment]
Thank you!
i have removed the EXT_ElseToogles and changed the tags (removed flop and added switch)

struggled on what would be the best wording from the start
i'm bad with linguistics i what to go with whatever you think would be the best wording for the end user

[ToggleValue-0.0.2.zip](https://github.com/4ian/GDevelop-extensions/files/5685337/ToggleValue-0.0.2.zip)
