### ISSUE TITLE
Konami Code

### ISSUE THREAD

**Issue by MercurioC** [4ian/GDevelop-extensions#8]
**Konami Code - by Tommaso "Giampiero" Bresciani**

Allows to input the classic Konami Code (*"Up, Up, Down, Down, Left, Right, Left, Right, B, A"*) into a scene for cheats and easter eggs.

To use it, simply attach the behavior to any object in a scene and use the Konami Code condition in the editor to trigger your desired effects with events.

## Checklist

- [ 🆗 ] Extension has a proper name and description.
- [ 🆗  ] Extension has tags (for example: "platform, brick, breakable").
- [ 🆗  ] All behaviors have a description.
- [ 🆗  ] All functions (actions, conditions, expressions) have descriptions.
- [ 🆗 ] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[KonamiCodeExtension.zip](https://github.com/4ian/GDevelop-extensions/files/3241070/KonamiCodeExtension.zip)

🙌

**Comment by 4ian** [comment]
Haha that's a great idea! Seems to be well done, easy to use and well explained - great job 👍

Added!
