### ISSUE TITLE
Extension to export GDevelop scenes to LDTK IntGrid layer

### ISSUE THREAD

**Issue by krunkster** [4ian/GDevelop-extensions#80]
## Description
Cursors through the current scene looking for collisions with platformer objects, and uses that information to populate a new LDTK file using a template LDTK project with a corresponding IntGrid.
Hopefully this will allow exporting levels designed in GDevelop into LDTK, which can then be exported to TMX and re-imported to GDevelop.😵
This is intended to bridge the gap for those of us who started using GDevelop before TMX support was added, but want to be able to "paint" their levels using LDTK.

Caveats:
- The input template LDTK file should have a world size smaller than the expected output, otherwise you will have to do some manual editing in LDTK to make it look right.
- You will need to hide/show all auto-render layers when you open the generated file to reapply the correct rendering.
- The int grid in the template file should have layers defined for "platform", "ladder", and "jumpthru" already or they will be added (but existing automapping will likely have to be redone)

## Extension file
[ExportPlatformsToIntGridForLDTK.zip](https://github.com/4ian/GDevelop-extensions/files/5698453/ExportPlatformsToIntGridForLDTK.zip)
This is the "export to file" version of the extension.

## Extension Demo Project
[PlatformToIntGridExporterForLDTK.zip](https://github.com/4ian/GDevelop-extensions/files/5698455/PlatformToIntGridExporterForLDTK.zip)
This is a sample project that demos how it can be used.

## Information
To be honest, I don't really want to create a supported extension, but I was doing this work for myself already to prepare for the work that @blurymind is doing.  I felt like it was good to share what I've come up with because I think it will help others in the same situation. I'm guessing @Silver-Streak would also be interested in this since I followed many of his comments on both LED (now LDTK) and GDevelop intersections.

**Comment by krunkster** [comment]
Related Issues:
TMX Support: https://github.com/4ian/GDevelop/pull/1901
LDTK Integration: https://github.com/4ian/GDevelop/issues/2002

**Comment by 4ian** [comment]
Very interesting! Not entirely sure if we should add it to the extensions registry now, but it might be later in a "tooling" category or something like that :)

**Comment by krunkster** [comment]
Just FYI incase anyone was using my extension code above, LDTK 8.x changes the way that intGridLayer coordinates are stored and breaks this code.
So use LDTK 7.x for the template files if you want to use this.

**Comment by arthuro555** [comment]
This should probably be closed as it probably won't be added and isn't compatible with newer versions of LDTK
