### ISSUE TITLE
Allow your object to float

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GDevelop-extensions#82]
## Describe the extension
Allow your object float up and down with linear effect to make it look smooth
Can custom the time it take and how long it can go

![image](https://user-images.githubusercontent.com/19387127/102516690-70172c80-408f-11eb-989b-de09b3b9c1d5.png)

![image](https://user-images.githubusercontent.com/19387127/102516454-23cbec80-408f-11eb-8495-aaaba86e2578.png)

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Preview
![floatgif](https://user-images.githubusercontent.com/19387127/102516221-e5cec880-408e-11eb-8490-017cd500e52f.gif)

## Extension file

As GitHub does not allow .json I ziped it

[FloatingEffect.zip](https://github.com/4ian/GDevelop-extensions/files/5720573/FloatingEffect.zip)

Hope this would help lots of people in the future. Thanks 🙌

**Comment by Jeje2201** [comment]
removed console.log + unused behavior

**Comment by 4ian** [comment]
We already have the tween behavior and a Sine movement behavior... I wonder if this won't do too much similar things? 🤔 The sine movement is pretty simple (no tweens involved), so is a bit more lightweight and is a behavior as you would expect it, so maybe we should just rework its description to say that we can use this to make object look like they are floating?

I see the idea behind this extension but I'm a bit afraid this would not provide sufficient value on top of the Tween behavior?

**Comment by Jeje2201** [comment]
Oh wow, I just tried the extension 😮 

Yeah indeed, it already does what I tried to implement, and his extension isn't based on the tween behavior, plus it can do x and y
I can also delete mine from my project and use this one that is way more simple to get and use

Thanks @4ian
