### ISSUE TITLE
Bug Auto typing extention

### ISSUE THREAD

**Issue by westboy31** [4ian/GDevelop-extensions#83]
Unable to assign conditions and actions to a BBText due to the same name of functions , even if it not the same behavior , Gdevelop give choice only for Text Object 
![2020-12-18 04_24_59-GDevelop 5 - C__Users_user_Documents_GDevelop projects_My project16_game json _](https://user-images.githubusercontent.com/49737293/102636181-9e127480-4154-11eb-8e3b-6855e05ab543.png)
![2020-12-18 04_27_21-GDevelop 5 - C__Users_user_Documents_GDevelop projects_My project16_game json _](https://user-images.githubusercontent.com/49737293/102636979-a0290300-4155-11eb-9bd8-1e0886dfb1da.png)

this is a game file with the bug :
[Auto typing bug game.zip](https://github.com/4ian/GDevelop-extensions/files/5716822/Auto.typing.bug.game.zip)

this is simple correction where we change the name functions display in the editor (works) :
[Auto typing extention correction.zip](https://github.com/4ian/GDevelop-extensions/files/5716830/Auto.typing.extention.correction.zip)

![2020-12-18 17_32_02-GDevelop 5 - C__Users_user_game   dev_gdevlop_type writing correction_Auto typin](https://user-images.githubusercontent.com/49737293/102637959-1417db00-4157-11eb-93ef-11d6b83b82bd.png)

**Comment by 4ian** [comment]
I think you're using the old action/condition editor right? If you switch to the new one, this kind of problem will entirely disappear :) We should by the way remove the old action/condition editor in the future.

Your workaround is also valid if you still want to use the old editor.

**Comment by westboy31** [comment]
> I think you're using the old action/condition editor right? If you switch to the new one, this kind of problem will entirely disappear :) We should by the way remove the old action/condition editor in the future.
> 
> Your workaround is also valid if you still want to use the old editor.

effectively, my bad, but i really hope you will keep the old condition action editors for future version , thank you.

**Comment by 4ian** [comment]
Can you quickly explain why you prefer the old editor? Is it searching in all actions/conditions that is easier? Or just an old habit?

**Comment by westboy31** [comment]
Of course this is subjective, but I find it more convenient to have all the events in the same tab window, switching between tab windows could waste time, and also habits play a role here , thank you for asking.
