### ISSUE TITLE
Create Random Color

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GDevelop-extensions#85]
## Describe the extension
Generate a string that create random color.

## How to use it
When typing a color code, just type "RandomColor"

![image](https://user-images.githubusercontent.com/19387127/102705161-a23daf80-4284-11eb-99bc-e2c98ddb2375.png)

## Preview

![RandomColor](https://user-images.githubusercontent.com/19387127/102705142-60ad0480-4284-11eb-95d1-4fc757a75442.gif)

## Checklist
- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file

[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/5720524/Extension.zip)

Hoping this would help some begginers. Thanks 🙌

**Comment by tristanbob** [comment]
I have talked with Jeje a little about this.  I want to add more parameters to this function to give users some control over the type of colors that are generated.  

Read some background here:
https://trello.com/c/4qGDGrJl/20-generaterandomcolor

**Comment by 4ian** [comment]
Thanks @Jeje2201! Looks good, I've pushed this initial version to the registry :) 
I've removed the "Trigger Once" though, I don't think it's necessary, and it's actually a problem if you use the expression more than once - it would then return an empty string! An expression is in theory always working :) 

> I have talked with Jeje a little about this. I want to add more parameters to this function to give users some control over the type of colors that are generated.

I think it's a great idea! Some more expressions giving choice about luminance/brightness/hue, etc... could be very useful. Feel free to open another issue when you have an update :)

**Comment by Jeje2201** [comment]
> I've removed the "Trigger Once" though, I don't think it's necessary, and it's actually a problem if you use the expression more than once - it would then return an empty string!

Indeed! Didn't think about the fact it could be use in a always action! 

> Looks good, I've pushed this initial version to the registry :)

Awesome! :)

**Comment by tristanbob** [comment]
Here is my proposal for adding inputs to this expression:
(Note: this requires using the HslToRgb() expression, or perhaps copying the code for it)

Default behavior with no inputs = Random color (same as now)

Input parameters:

Min hue: range(0,360), default=0
Max hue: range(0,360), default=360

Min saturation: range(0,100), default=0
Max saturation: range(0,100), default=100

Min lightness: range(0,100), default=0
Max lightness: range(0,100), default=100

These options will let you choose a LOT of types of colors:

greyscale (max saturation = 0)
pure colors (min saturation = 100)
pastels (min/max saturation = ~80, min/max lightness = ~80)
red tints (min/max hue = 0)

What do you think about these inputs?

**Comment by 4ian** [comment]
That's very interesting :) We can:

- keep a "totally random color" expression.
- have a "random color with min and max values for HSL" that you described (6 parameters: min/max hue/saturation/lightness).
- have a few additional helpers to make things easier: `CreateRandomGreyscaleColor`, `CreateRandomPastelColor`, `CreateRandomSaturatedColor`...

**Comment by tristanbob** [comment]
@4ian I like all 3!  It provides a super simple option (1), a small menu option (3), and full customization for power users (2).

**Comment by 4ian** [comment]
Yep 👍 Sounds good then!

**Comment by tristanbob** [comment]
Do you have a preference on how to integrate the "HslToRgb()" expression?  

Should RandomColor and ColorConversions be combined into one extension with multiple expressions?

**Comment by 4ian** [comment]
For now you could maybe just copy paste the required JS code/expression?
