### ISSUE TITLE
Update:  TravelToRandomPositions-0.3.0 

### ISSUE THREAD

**Issue by tristanbob** [4ian/GDevelop-extensions#89]
Changes include:

- Users can specify a direction to head towards, with a direction bias
 -- Direction bias (Range: 0-1)  0 is a random direction, and 1 always uses the specified direction.
 -- This can be used to make objects chase (or run away from) the player, or to make objects cross the screen using a meandering path.
- Logic will now only run when needed (pathfinding speed=0)
- Changed to child structure variables

[TravelToRandomPositions-0.3.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/5749704/TravelToRandomPositions-0.3.0.json.zip)

https://user-images.githubusercontent.com/8879811/103261186-c0c73900-495d-11eb-809f-a0d4a378fa65.mp4

https://user-images.githubusercontent.com/8879811/103262910-852f6d80-4963-11eb-891f-fb332963e5c9.mp4

**Comment by tristanbob** [comment]
Hold on importing this.  

I am making an example that has enemies that move away and some that move towards the player... and I realized that I need to change from scene variables to object variables!

**Comment by 4ian** [comment]
Sounds good then :) 
For parameters that need a longer description, feel free to use the Long description field: 
![image](https://user-images.githubusercontent.com/1280130/103317171-fd149b00-4a2a-11eb-9e11-70173c244499.png)

As usual please ping me here when you have the extension ready!

**Comment by tristanbob** [comment]
I have changed that parameter to a long description.

v0.4.0 changes:

- Converted all scene variables to object variables 
- Tested this with a large herd of objects at the same time and it worked well.
- I can envision this enabling MANY different types of uses, which I intend to share with an example game and a walk-through video.

[TravelToRandomPositions-0.4.0.json.zip](https://github.com/4ian/GDevelop-extensions/files/5752558/TravelToRandomPositions-0.4.0.json.zip)

**Comment by tristanbob** [comment]
Updated video:

https://user-images.githubusercontent.com/8879811/103322147-426ca480-49fa-11eb-835a-877f3de95014.mp4

**Comment by 4ian** [comment]
Updated, thanks! 

The biais is 0 to tell "full circle" and 1 to tell "exactly the specified angle". Should it be the reverse? When I read "biais: 0", I think "no biais, so the exact thing that was entered"?

**Comment by tristanbob** [comment]
If the extension was called "Travel in a direction, with optional randomness", then maybe we would change "direction bias" to "level of randomness", where 0=straight and 1=random.

However, since this is called "Travel to Random Positions" I think it makes sense for "direction bias" function with 0=random and 1=straight.
