### ISSUE TITLE
border

### ISSUE THREAD

**Issue by derric-young** [4ian/GDevelop-extensions#92]
this is a extenshion ment to make creating borders easier with 1 event

border
idk
there are none
yes they do
yes i confirm this

https://github.com/derric-young/border-extenshion

**Comment by Bouh** [comment]
Hello thank you for your first extension!

We have some standard before make a complete review, as the extension are dirrectly in the app we hope see more and more polised extensions.
[Here a first step how write a great extension with ours standard.](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices)
