### ISSUE TITLE
Double-Click Extension

### ISSUE THREAD

**Issue by Silver-Streak** [4ian/GDevelop-extensions#95]
## Describe the extension
This extension adds conditions to check for double-clicking with the left, middle, and right mouse buttons (or double-taps on touch devices). It includes a customizable timer for double-click speed.

## Checklist

- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions.
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[DoubleClick1-0-1.zip](https://github.com/4ian/GDevelop-extensions/files/5796449/DoubleClick1-0-1.zip)

**Comment by Bouh** [comment]
- `Touch or _PARAM2_ mouse is double-clicked or double-tapped within _PARAM1_ seconds`
It's same model as the current click and touch condition.
- There is no period in the eventsheet, but in the description we add period.

**Comment by 4ian** [comment]
Nice work :) I've reworked a bit the extension:
* remove useless Trigger Once
* Used sub events to avoid redundant conditions
* Added an action to define the default delay between two clicks (set by default to 0.5)
* Fixed the events sheet sentence (no "if blabla", all conditions are already some "if" implicitly)
* Normalized the variable prefixes to be `__ExtensionName_`

Thanks for submitting this :)
