### ISSUE TITLE
Noise extension update

### ISSUE THREAD

**Issue by Add00** [4ian/GDevelop-extensions#96]
## Describe the extension
Just a small minor update to incorporate Bouh's feedback.

- Added a help link to the procedural generation section of the wiki
- I noticed that PascalCase was missing from the function names, so I added it
- I also submitted an [example](https://github.com/4ian/GDevelop/issues/2214) project, showcasing the extension 

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [x] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Extension file
[Noise.zip](https://github.com/4ian/GDevelop-extensions/files/5821069/Noise.zip)

**Comment by 4ian** [comment]
Excellent, thanks! 👍
